window.V6_AUTHENTIC_SOURCES = [
  {
    "id": "aio_salamis_1672",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Decree about the Athenian cleruchy on Salamis",
    "author": "Athenian People",
    "canonical_ref": "AIO 1672 = IG I³ 1 = ML 14",
    "period": "508–500 BC?",
    "place": "Athens / Salamis",
    "original_text": "ἔδοχσεν το͂ι δέμοι· τ̣[ὸς ἐΣ]αλαμ̣[ῖνι κλερόχ]ος οἰκε͂ν ἐᾶ Σαλαμῖνι ... Ἀθένεσι τελε͂ν καὶ στρατ[εύεσθ]αι ...",
    "translation_text": "The People decided: those holding allotments on Salamis are to be allowed to reside there ... at Athens they are to pay taxes and perform military service.",
    "original_source_name": "Attic Inscriptions Online — Greek text, AIO 1672",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIO/1672?text_type=greek",
    "translation_source_name": "AIO translated text — Stephen Lambert & Julian Schneider",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIO/1672",
    "translation_credit": "Scriptorium working translation checked against AIO.",
    "context_hint": "Public decree; fragmentary inscription. Brackets and dots signal editorial restoration or loss.",
    "language_hint": "Treat restored letters differently from preserved letters.",
    "analytic_hint": "Separate what the decree prescribes from what people demonstrably did.",
    "scaffold": [
      "What is preserved?",
      "What is restored?",
      "What is normative?",
      "What would require another source type?"
    ],
    "tags": [
      "decree",
      "law",
      "citizenship",
      "taxation",
      "military",
      "epigraphy"
    ],
    "recommended_modules": [
      "m03",
      "m04",
      "m05",
      "m08",
      "m10",
      "m11",
      "m17",
      "m18",
      "m21"
    ]
  },
  {
    "id": "thuc_2_37",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "grc",
    "title": "Funeral Oration: democracy and equality",
    "author": "Thucydides",
    "canonical_ref": "Thuc. 2.37.1",
    "period": "late 5th c. BC",
    "place": "Athens",
    "original_text": "καὶ ὄνομα μὲν διὰ τὸ μὴ ἐς ὀλίγους ἀλλ’ ἐς πλείονας οἰκεῖν δημοκρατία κέκληται· μέτεστι δὲ κατὰ μὲν τοὺς νόμους ... πᾶσι τὸ ἴσον.",
    "translation_text": "It is called a democracy because administration is in the hands of the many rather than the few; under the laws, equality is available to all in private disputes.",
    "original_source_name": "Perseus/Scaife — Greek edition of Thucydides",
    "original_source_url": "https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0003.tlg001.perseus-grc2:2.37.1/",
    "translation_source_name": "Perseus — Richard Crawley, 1910",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0200%3Abook%3D2%3Achapter%3D37%3Asection%3D1",
    "translation_credit": "Scriptorium working translation checked against Crawley.",
    "context_hint": "Thucydides presents Pericles' funeral speech; rhetorical setting and authorial mediation are central.",
    "language_hint": "δημοκρατία and τὸ ἴσον are analytically loaded terms, not transparent measurements.",
    "analytic_hint": "Do not equate political self-description with an exhaustive institutional description.",
    "scaffold": [
      "Who is speaking?",
      "For what audience?",
      "What is normative praise?",
      "What independent evidence could test the claims?"
    ],
    "tags": [
      "democracy",
      "rhetoric",
      "politics",
      "literary",
      "representation"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m06",
      "m07",
      "m09",
      "m11",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "herodotus_5_78",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "grc",
    "title": "Herodotus on isēgoriē and Athenian power",
    "author": "Herodotus",
    "canonical_ref": "Hdt. 5.78",
    "period": "5th c. BC",
    "place": "Athens",
    "original_text": "δηλοῖ δὲ ... ἡ ἰσηγορίη ὡς ἔστι χρῆμα σπουδαῖον ... ἀπαλλαχθέντες δὲ τυράννων μακρῷ πρῶτοι ἐγένοντο.",
    "translation_text": "It is evident that equality of political speech is a powerful thing: after the Athenians were rid of tyrants, they became markedly pre-eminent.",
    "original_source_name": "Perseus — Greek text of Herodotus",
    "original_source_url": "https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0016.tlg001.perseus-grc2:5.78/",
    "translation_source_name": "G. C. Macaulay translation, 1890",
    "translation_source_url": "https://lexundria.com/hdt/5.78/mcly",
    "translation_credit": "Scriptorium working translation checked against Macaulay.",
    "context_hint": "Narrative explanation written after the events; the passage explicitly links political regime and military performance.",
    "language_hint": "ἰσηγορίη is a contested political term; do not silently equate it with a complete modern model of democracy.",
    "analytic_hint": "The passage contains a causal claim. Ask what alternative mechanisms could produce the same observed outcome.",
    "scaffold": [
      "What is the observed change?",
      "What cause does Herodotus propose?",
      "What evidence is missing?",
      "What rival explanation would you test?"
    ],
    "tags": [
      "causality",
      "democracy",
      "tyranny",
      "military",
      "literary"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m09",
      "m11",
      "m12",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "caesar_bg_1_1",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "lat",
    "title": "Caesar's opening ethnography of Gaul",
    "author": "Julius Caesar",
    "canonical_ref": "Caes. BG 1.1",
    "period": "mid-1st c. BC",
    "place": "Gaul",
    "original_text": "Gallia est omnis divisa in partes tres ... Hi omnes lingua, institutis, legibus inter se differunt.",
    "translation_text": "Gaul as a whole is divided into three parts ... these peoples differ from one another in language, customs and laws.",
    "original_source_name": "Perseus — T. Rice Holmes Latin edition, 1914",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0002%3Abook%3D1%3Achapter%3D1",
    "translation_source_name": "W. A. McDevitte & W. S. Bohn translation, 1869",
    "translation_source_url": "https://atlas.perseus.tufts.edu/library/urn%3Acts%3AlatinLit%3Aphi0448.phi001.perseus-eng2/",
    "translation_credit": "Scriptorium working translation checked against McDevitte & Bohn.",
    "context_hint": "A commander-author classifies peoples at the opening of a conquest narrative.",
    "language_hint": "Notice categorical verbs and group labels. They create analytical units before evidence is presented.",
    "analytic_hint": "Treat Caesar's ethnographic categories as claims requiring testing, not neutral dataset labels.",
    "scaffold": [
      "Who creates the categories?",
      "What function do they serve?",
      "Could local variation disappear?",
      "What source could test them?"
    ],
    "tags": [
      "ethnography",
      "categories",
      "empire",
      "literary",
      "representation"
    ],
    "recommended_modules": [
      "m03",
      "m04",
      "m05",
      "m07",
      "m09",
      "m11",
      "m14",
      "m17",
      "m22"
    ]
  },
  {
    "id": "cicero_cat_1_1",
    "primary": true,
    "ready": true,
    "source_type": "speech",
    "language": "lat",
    "title": "Cicero's opening attack on Catiline",
    "author": "Cicero",
    "canonical_ref": "Cic. Cat. 1.1",
    "period": "63 BC",
    "place": "Rome",
    "original_text": "Quo usque tandem abutere, Catilina, patientia nostra? Quam diu etiam furor iste tuus nos eludet? Quem ad finem sese effrenata iactabit audacia?",
    "translation_text": "How long, Catiline, will you continue to abuse our patience? How much longer will that madness of yours evade us? How far will your unrestrained audacity go?",
    "original_source_name": "Perseus — A. C. Clark Latin edition, 1908",
    "original_source_url": "https://atlas.perseus.tufts.edu/library/urn%3Acts%3AlatinLit%3Aphi0474.phi013.perseus-lat2/",
    "translation_source_name": "C. D. Yonge translation, 1856",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0019%3Atext%3DCatil.%3Aspeech%3D1%3Achapter%3D1",
    "translation_credit": "Scriptorium working translation checked against Yonge.",
    "context_hint": "A highly adversarial senatorial speech. Accusation, persuasion and performance shape the evidence.",
    "language_hint": "The repeated rhetorical questions and loaded nouns are argumentative devices.",
    "analytic_hint": "A speech can reveal political strategies and categories even where it cannot independently establish every alleged fact.",
    "scaffold": [
      "Which statements are accusation?",
      "Which are observable circumstances?",
      "Who is the audience?",
      "What would corroboration look like?"
    ],
    "tags": [
      "rhetoric",
      "politics",
      "elite",
      "speech",
      "bias"
    ],
    "recommended_modules": [
      "m05",
      "m06",
      "m07",
      "m09",
      "m11",
      "m16",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "pliny_ep_10_96",
    "primary": true,
    "ready": true,
    "source_type": "letter",
    "language": "lat",
    "title": "Pliny asks Trajan how to handle Christians",
    "author": "Pliny the Younger",
    "canonical_ref": "Plin. Ep. 10.96.1",
    "period": "c. AD 112",
    "place": "Bithynia-Pontus",
    "original_text": "Sollemne est mihi, domine, omnia de quibus dubito ad te referre ... Cognitionibus de Christianis interfui numquam: ideo nescio quid et quatenus aut puniri soleat aut quaeri.",
    "translation_text": "It is my regular practice, lord, to refer to you everything about which I am uncertain ... I have never attended investigations of Christians, so I do not know what is usually punished or investigated, or to what extent.",
    "original_source_name": "Perseus — Latin text of Pliny, Epistles 10.96",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Plin.+Ep.+10.96",
    "translation_source_name": "Perseus/Scaife English translation record for Pliny's Letters",
    "translation_source_url": "https://scaife.perseus.org/",
    "translation_credit": "Scriptorium working translation from the Latin; external translation link for checking.",
    "context_hint": "Official correspondence from a provincial governor to the emperor. It records uncertainty and administrative decision-making.",
    "language_hint": "Pliny explicitly marks his uncertainty with dubito, nescio and questions about procedure.",
    "analytic_hint": "This is strong evidence for Pliny's problem and procedure, but not automatically for the prevalence or beliefs of all Christians.",
    "scaffold": [
      "What does Pliny know?",
      "What does he admit he does not know?",
      "What is administrative practice?",
      "What is evidence about Christians themselves?"
    ],
    "tags": [
      "letter",
      "governance",
      "religion",
      "procedure",
      "uncertainty",
      "province"
    ],
    "recommended_modules": [
      "m05",
      "m08",
      "m10",
      "m11",
      "m13",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "rgda_34",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "lat",
    "title": "Augustus on the constitutional settlement",
    "author": "Augustus",
    "canonical_ref": "Res Gestae 34",
    "period": "text completed by AD 14",
    "place": "Rome / Ankara copy",
    "original_text": "Post id tempus auctoritate omnibus praestiti, potestatis autem nihilo amplius habui quam ceteri qui mihi quoque in magistratu conlegae fuerunt.",
    "translation_text": "After that time I surpassed everyone in authority, but I possessed no more formal power than the others who were my colleagues in each magistracy.",
    "original_source_name": "Perseus — Latin text, Res Gestae 34",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=urn%3Acts%3AlatinLit%3Aphi1221.phi007.perseus-lat1%3A34",
    "translation_source_name": "LacusCurtius — F. W. Shipley, Loeb 1924 (public-domain text)",
    "translation_source_url": "https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Augustus/Res_Gestae/home.html",
    "translation_credit": "Scriptorium working translation checked against Shipley.",
    "context_hint": "Programmatic first-person political self-representation, preserved epigraphically in the provinces.",
    "language_hint": "Distinguish auctoritas from potestas; the contrast is part of Augustus' claim.",
    "analytic_hint": "Do not convert constitutional self-description into a neutral description of actual power.",
    "scaffold": [
      "What distinction does Augustus construct?",
      "Who benefits from this framing?",
      "What evidence could test de facto power?",
      "Why does epigraphic display matter?"
    ],
    "tags": [
      "princeps",
      "power",
      "self-representation",
      "inscription",
      "constitution"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m07",
      "m09",
      "m10",
      "m11",
      "m12",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "rib_1065_regina",
    "primary": true,
    "ready": true,
    "source_type": "funerary_inscription",
    "language": "lat",
    "title": "Funerary inscription for Regina",
    "author": "Barates (dedicator)",
    "canonical_ref": "RIB 1065",
    "period": "2nd century AD",
    "place": "Arbeia / South Shields",
    "original_text": "D(is) M(anibus) Regina liberta et coniuge Barates Palmyrenus natione Catuallauna an(norum) XXX",
    "translation_text": "To the spirits of the departed, and to Regina, his freedwoman and wife, a Catuvellaunian by origin, aged thirty: Barates of Palmyra set this up.",
    "original_source_name": "Roman Inscriptions of Britain — RIB 1065",
    "original_source_url": "https://romaninscriptionsofbritain.org/inscriptions/1065",
    "translation_source_name": "Roman Inscriptions of Britain — translation",
    "translation_source_url": "https://romaninscriptionsofbritain.org/inscriptions/1065",
    "translation_credit": "Scriptorium working rendering checked against RIB.",
    "context_hint": "Bilingual funerary monument; RIB also records a Palmyrene text. Commemoration is selective social representation.",
    "language_hint": "Abbreviations such as D.M. and ann. are formulaic. Grammatical irregularity itself may be historically meaningful.",
    "analytic_hint": "Do not infer a complete household biography from what the commemorator chose to inscribe.",
    "scaffold": [
      "Who commemorates whom?",
      "Which identities are named?",
      "Which are omitted?",
      "What does bilingualism allow you to ask?"
    ],
    "tags": [
      "funerary",
      "migration",
      "freedwoman",
      "identity",
      "bilingualism",
      "epigraphy"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m14",
      "m17",
      "m21",
      "m22"
    ]
  },
  {
    "id": "vindolanda_291",
    "primary": true,
    "ready": true,
    "source_type": "writing_tablet",
    "language": "lat",
    "title": "Birthday invitation from Claudia Severa to Sulpicia Lepidina",
    "author": "Claudia Severa",
    "canonical_ref": "Tab. Vindol. 291",
    "period": "c. AD 100",
    "place": "Vindolanda",
    "original_text": "Cl(audia) Seuerá Lepidinae suae salutem. iii Idus Septembres, soror, ad diem sollemnem natalem meum rogo libenter facias ut uenias ad nos ...",
    "translation_text": "Claudia Severa sends greetings to her Lepidina. Sister, on 11 September, for the celebration of my birthday, I warmly ask you to make sure that you come to us ...",
    "original_source_name": "Roman Inscriptions of Britain — TabVindol 291",
    "original_source_url": "https://romaninscriptionsofbritain.org/inscriptions/TabVindol291",
    "translation_source_name": "Roman Inscriptions of Britain — translation",
    "translation_source_url": "https://romaninscriptionsofbritain.org/inscriptions/TabVindol291",
    "translation_credit": "Scriptorium working translation checked against RIB.",
    "context_hint": "Private wooden writing tablet from the military frontier; a rare documentary glimpse of elite women's social networks.",
    "language_hint": "Epistolary formulae and spelling should be distinguished from analytical content.",
    "analytic_hint": "Exceptional preservation makes the source valuable but not automatically representative.",
    "scaffold": [
      "What relationship is directly attested?",
      "What social practices are only implied?",
      "Why was this preserved?",
      "What comparison would test representativeness?"
    ],
    "tags": [
      "letter",
      "women",
      "frontier",
      "social-network",
      "documentary",
      "material"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m14",
      "m17",
      "m21",
      "m22"
    ]
  },
  {
    "id": "poxy_4_744",
    "primary": true,
    "ready": true,
    "source_type": "papyrus_letter",
    "language": "grc",
    "title": "Hilarion to Alis",
    "author": "Hilarion",
    "canonical_ref": "P.Oxy. IV 744",
    "period": "1 BC",
    "place": "Oxyrhynchus / Alexandria",
    "original_text": "ἐρωτῶ σε καὶ παρακαλῶ σε ἐπιμελήθι τῷ παιδίῳ ... ἐὰν ἦν ἄρσενον ἄφες, ἐὰν ἦν θήλεα ἔκβαλε.",
    "translation_text": "I ask and urge you to take care of the child ... if it is male, let it remain; if it is female, expose it.",
    "original_source_name": "DDbDP transcription, P.Oxy. IV 744",
    "original_source_url": "https://papyri.info/ddbdp/p.oxy;4;744",
    "translation_source_name": "Select Papyri 1.105 / Attalus",
    "translation_source_url": "https://www.attalus.org/docs/select1/p105.html",
    "translation_credit": "Scriptorium working translation checked against the published English selection.",
    "context_hint": "Private letter, not a legal prescription or population-level dataset. Its documentary immediacy does not erase individual context.",
    "language_hint": "The papyrus preserves non-classical spellings and grammar; editorial normalization can conceal historically useful linguistic evidence.",
    "analytic_hint": "One shocking instruction cannot by itself establish prevalence, normality or legal status of a practice.",
    "scaffold": [
      "What is directly instructed?",
      "What broader practice is not demonstrated?",
      "What comparison is required?",
      "Which kind of conclusion is proportionate?"
    ],
    "tags": [
      "papyrus",
      "letter",
      "family",
      "gender",
      "documentary",
      "representativeness"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m17",
      "m21",
      "m22"
    ]
  },
  {
    "id": "ocre_aug_86a",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Augustus denarius: SIGNIS RECEPTIS",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 86A",
    "period": "19–15 BC",
    "place": "Colonia Patricia",
    "original_text": "Obverse legend: CAESAR AVGVSTVS. Reverse legend: SIGNIS RECEPTIS. Reverse type: shield marked CL V, flanked by an aquila and a military standard.",
    "translation_text": "Object data rather than a translated text: the reverse publicly evokes the recovery of military standards and the clipeus virtutis.",
    "original_source_name": "Online Coins of the Roman Empire — RIC I² Augustus 86A",
    "original_source_url": "http://numismatics.org/ocre/id/ric.1(2).aug.86A",
    "translation_source_name": "OCRE object/legend record",
    "translation_source_url": "http://numismatics.org/ocre/id/ric.1(2).aug.86A",
    "translation_credit": "No literary translation: Scriptorium preserves the legend and object description; interpretation must be argued.",
    "context_hint": "Minted object with official iconographic and textual choices; circulation is not the same thing as proven audience reception.",
    "language_hint": "Expand AVGVSTVS and SIGNIS RECEPTIS, but keep expansion separate from historical interpretation.",
    "analytic_hint": "Coin imagery is excellent evidence for messages made available in circulation, weaker evidence for what every viewer believed.",
    "scaffold": [
      "What is physically on the coin?",
      "What is iconographic interpretation?",
      "Who issued it?",
      "How would circulation/reception be tested?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "Augustus",
      "military",
      "iconography",
      "reception"
    ],
    "recommended_modules": [
      "m03",
      "m04",
      "m05",
      "m10",
      "m11",
      "m14",
      "m17",
      "m21",
      "m22"
    ]
  },
  {
    "id": "aio_aiuk2_8",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "List of Athenians and Romans",
    "author": "Unknown civic/associational context",
    "canonical_ref": "AIUK 2 no. 8 = IG II² 2460",
    "period": "c. 100–90 BC",
    "place": "Athens",
    "original_text": "Ἀλκέτου τοῦ Εὐαγίωνος Περιθοίδου ... Λευκίου τοῦ Λευκίου ῾Ρωμαίου Μαάρκου τοῦ Μαάρκου ῾Ρωμαίου ...",
    "translation_text": "The list names Athenians by deme and also Lucius son of Lucius and Marcus son of Marcus, identified as Romans.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIUK2/8?text_type=greek",
    "translation_source_name": "AIO translation by Stephen Lambert",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIUK2/8",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "A list without its lost wider context. Prosopography can suggest networks, but the original purpose is uncertain.",
    "language_hint": "Ethnics/demotics identify civic affiliations; names alone do not establish social role.",
    "analytic_hint": "Do not infer a complete Roman community from two Roman names in one fragmentary list.",
    "scaffold": [
      "What is directly listed?",
      "What context is missing?",
      "Which prosopographic inference is defensible?",
      "What comparison would test significance?"
    ],
    "tags": [
      "prosopography",
      "Romans",
      "Athens",
      "list",
      "identity"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m14",
      "m21"
    ]
  },
  {
    "id": "aio_ro22",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Second Athenian League decree",
    "author": "Athenian Council and People",
    "canonical_ref": "RO 22 = IG II² 43",
    "period": "378/7 BC",
    "place": "Athens",
    "original_text": "ἔδοξεν τῆι βολῆι καὶ τῶι δήμωι ... ἐλευθέρους καὶ αὐτονόμους ... μήτε φρουρὰν ... μήτε φόρον φέροντι ...",
    "translation_text": "The decree presents prospective allies as free and autonomous, without an Athenian garrison, governor, or tribute.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/RO/22?text_type=greek",
    "translation_source_name": "AIO translation by Stephen Lambert & P. J. Rhodes",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/RO/22",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "Alliance decree deliberately defines acceptable interstate relations after memories of fifth-century Athenian empire.",
    "language_hint": "ἐλευθερία, αὐτονομία and φόρος are politically charged terms.",
    "analytic_hint": "Treat promises in an alliance decree as normative commitments, then test later practice separately.",
    "scaffold": [
      "What commitments are explicit?",
      "What historical memory may shape them?",
      "What later evidence could test compliance?"
    ],
    "tags": [
      "alliance",
      "autonomy",
      "empire",
      "decree",
      "norm-practice"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m07",
      "m10",
      "m11",
      "m12",
      "m17",
      "m21"
    ]
  },
  {
    "id": "aio_aiuk9_pan",
    "primary": true,
    "ready": true,
    "source_type": "dedication",
    "language": "grc",
    "title": "Dedication to Pan and the Nymphs",
    "author": "Private dedicator from Phlya",
    "canonical_ref": "AIUK 9 Appendix 1 = IG II³ 4, 1430",
    "period": "c. 350–330 BC",
    "place": "Attica",
    "original_text": "[- - - - - - ί]π̣πο Φλυεὺς ἀνέθηκεν.",
    "translation_text": "A man of Phlya, whose name is partly lost, dedicated the object.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIUK9/appendix-1?text_type=greek",
    "translation_source_name": "AIO translation by Peter Liddel & Polly Low",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIUK9/appendix-1",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "The inscribed relief survives through an early modern depiction; object, image and text have different transmission histories.",
    "language_hint": "ἀνέθηκεν marks dedication; the lost name limits social identification.",
    "analytic_hint": "Material context and survival history are part of source criticism, not decoration.",
    "scaffold": [
      "What survives physically?",
      "What survives only through a drawing?",
      "What can the demotic tell you?"
    ],
    "tags": [
      "dedication",
      "religion",
      "relief",
      "material-culture",
      "transmission"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m21"
    ]
  },
  {
    "id": "aio_igi3_246",
    "primary": true,
    "ready": true,
    "source_type": "sacrificial_calendar",
    "language": "grc",
    "title": "Sacrificial calendar",
    "author": "Local Attic community",
    "canonical_ref": "IG I³ 246 = AIUK 4.1 no. 2",
    "period": "470–450 BC",
    "place": "Attica",
    "original_text": "Πλυντερίοισι Ἀθεναίαι οἶν ... Hέρμει πυρῶν δύο χοίνικε ...",
    "translation_text": "At the Plynteria a sheep is assigned to Athena; another entry specifies two choenices of wheat for Hermes.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIUK41/2?text_type=greek",
    "translation_source_name": "AIO translation by Stephen Lambert & Feyo Schuddeboom",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIUK41/2",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "A fragmentary ritual calendar inscribed on multiple faces; its original findspot is unknown.",
    "language_hint": "Archaic orthography and damaged text complicate normalization.",
    "analytic_hint": "Prescribed offerings reveal institutional ritual provision, not automatically actual attendance or belief.",
    "scaffold": [
      "Which entries are certain?",
      "What does a calendar regulate?",
      "Which social practices remain invisible?"
    ],
    "tags": [
      "religion",
      "calendar",
      "ritual",
      "fragmentary",
      "epigraphy"
    ],
    "recommended_modules": [
      "m05",
      "m08",
      "m10",
      "m11",
      "m13",
      "m21"
    ]
  },
  {
    "id": "aio_802_chios",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Alliance with Chios",
    "author": "Athenian Council and People",
    "canonical_ref": "AIO 802",
    "period": "384/3 BC",
    "place": "Athens",
    "original_text": "συμμάχους ποιεῖσθαι Χίους ἐπ’ ἐλευθερίαι καὶ αὐτονομίαι ... βοηθεῖν ... παντὶ σθένει ...",
    "translation_text": "The Chians are to become allies on terms of freedom and autonomy, with mutual military assistance.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIO/802?text_type=greek",
    "translation_source_name": "Attic Inscriptions Online translated record",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIO/802",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "Formal alliance provisions encode an ideal interstate relationship.",
    "language_hint": "Pay attention to reciprocal conditional clauses and the formula κατὰ τὸ δυνατόν.",
    "analytic_hint": "Mutual obligation on stone is evidence for negotiated norms, not proof of later equal performance.",
    "scaffold": [
      "Which obligations are reciprocal?",
      "Where is discretion preserved?",
      "How could later behaviour be tested?"
    ],
    "tags": [
      "alliance",
      "autonomy",
      "diplomacy",
      "decree"
    ],
    "recommended_modules": [
      "m05",
      "m10",
      "m11",
      "m12",
      "m17",
      "m21"
    ]
  },
  {
    "id": "aio_807_dionysios",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Alliance with Dionysios I of Syracuse",
    "author": "Athenian People",
    "canonical_ref": "AIO 807",
    "period": "368/7 BC?",
    "place": "Athens",
    "original_text": "ἐπαινέσαι ... Διονύσιον ... σύμμαχον ... ἐάν τις ἴηι ἐπὶ τὴν χώραν ... βοηθεῖν ...",
    "translation_text": "The decree praises Dionysios and establishes mutual assistance if either party is attacked.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIO/807?text_type=greek",
    "translation_source_name": "Attic Inscriptions Online translated record",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIO/807",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "Diplomatic honorific language and treaty clauses coexist in one public text.",
    "language_hint": "Separate praise formulae from operative clauses.",
    "analytic_hint": "Different parts of one inscription can have different evidential status.",
    "scaffold": [
      "Which words praise?",
      "Which clauses create obligations?",
      "Which historical claim relies on which part?"
    ],
    "tags": [
      "diplomacy",
      "treaty",
      "ruler",
      "decree",
      "genre"
    ],
    "recommended_modules": [
      "m05",
      "m10",
      "m11",
      "m16",
      "m17",
      "m21"
    ]
  },
  {
    "id": "aio_or155_coinage",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Decree enforcing Athenian coins, weights and measures",
    "author": "Athenian authorities",
    "canonical_ref": "OR 155 = IG I³ 1453",
    "period": "c. 414 BC?",
    "place": "Athenian sphere",
    "original_text": "ἐάν τις κόπτηι νόμισμα ... καὶ μὴ χρῆται νομίσμασιν τοῖς Ἀθηναίων ἢ σταθμοῖς ἢ μέτροις ...",
    "translation_text": "The decree penalizes minting or using currency, weights, or measures contrary to the Athenian standards it prescribes.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/IGI3/1453?text_type=greek",
    "translation_source_name": "Attic Inscriptions Online translated record",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/IGI3/1453",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "Highly fragmentary coercive regulation linked to Athenian economic standards.",
    "language_hint": "Editorial restorations materially affect how the regulatory mechanism is reconstructed.",
    "analytic_hint": "Enforcement provisions indicate state intention; actual monetary circulation needs numismatic evidence.",
    "scaffold": [
      "What is normatively required?",
      "Where is the text restored?",
      "What coin evidence could corroborate practice?"
    ],
    "tags": [
      "coinage",
      "weights",
      "measures",
      "empire",
      "economy",
      "law"
    ],
    "recommended_modules": [
      "m05",
      "m10",
      "m11",
      "m12",
      "m13",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_127",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Aureus: RIC I² Augustus 127",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 127",
    "period": "18–17 BC",
    "place": "Colonia Patricia",
    "original_text": "Legend: AVGVSTVS. Type: Capricorn holding globe with rudder; cornucopia above.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://www.numismatics.org/ocre/id/ric.1%282%29.aug.127",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://www.numismatics.org/ocre/id/ric.1%282%29.aug.127",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_253",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC I² Augustus 253",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 253",
    "period": "32–29 BC",
    "place": "uncertain Italian mint",
    "original_text": "Legend: CAESAR DIVI F. Type: Octavian in military dress, with spear.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.253",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.253",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_11a",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "As: RIC I² Augustus 11A",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 11A",
    "period": "25–23 BC",
    "place": "Caesaraugusta",
    "original_text": "Legend: P CARISIVS LEG AVGVSTI EMERITA. Type: City wall and gateway marked EMERITA.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.11A",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.11A",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_126",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC I² Augustus 126",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 126",
    "period": "18–17 BC",
    "place": "Colonia Patricia",
    "original_text": "Legend: AVGVSTVS. Type: Capricorn with globe, rudder and cornucopia.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.126",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.126",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_220",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC I² Augustus 220",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 220",
    "period": "AD 13–14",
    "place": "Lugdunum",
    "original_text": "Legend: PONTIF MAXIM. Type: Seated female figure holding branch and sceptre.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://www.numismatics.org/ocre/id/ric.1%282%29.aug.220",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://www.numismatics.org/ocre/id/ric.1%282%29.aug.220",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_160",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "As: RIC I² Augustus 160",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 160",
    "period": "AD 10–14",
    "place": "Nemausus",
    "original_text": "Legend: COL NEM. Type: Crocodile chained to palm; Augustus and Agrippa on obverse.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.160",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.160",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_256",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC I² Augustus 256",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 256",
    "period": "32–29 BC",
    "place": "uncertain Italian mint",
    "original_text": "Legend: CAESAR DIVI F. Type: Victory bust; Neptune with globe, aplustre and spear.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.256",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.256",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_tib_30",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC I² Tiberius 30",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Tiberius 30",
    "period": "AD 14–37",
    "place": "Lugdunum",
    "original_text": "Legend: PONTIF MAXIM. Type: Seated female figure with branch and sceptre.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.tib.30",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.tib.30",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_nero_101",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Sestertius: RIC I² Nero 101",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Nero 101",
    "period": "AD 62–68",
    "place": "Rome",
    "original_text": "Legend: CONG II DAT POP. Type: Imperial distribution scene with citizens, Minerva and Liberalitas.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.ner.101",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.ner.101",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_nero_269",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Sestertius: RIC I² Nero 269",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Nero 269",
    "period": "AD 62–68",
    "place": "Rome",
    "original_text": "Legend: PACE P R TERRA MARIQ PARTA IANVM CLVSIT S C. Type: Temple of Janus with closed doors.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.ner.269",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.ner.269",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_trajan_318",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC II Trajan 318",
    "author": "Roman mint authority",
    "canonical_ref": "RIC II Trajan 318",
    "period": "AD 114",
    "place": "Rome",
    "original_text": "Legend: P M TR P COS VI P P S P Q R FORT RED. Type: Fortuna with rudder and cornucopia.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.2.tr.318_denarius",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.2.tr.318_denarius",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "tac_agric_30_6",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "lat",
    "title": "Calgacus' speech on Roman imperialism",
    "author": "Tacitus",
    "canonical_ref": "Tac. Agr. 30.6",
    "period": "c. AD 98",
    "place": "Britain (narrative setting)",
    "original_text": "auferre trucidare rapere falsis nominibus imperium, atque ubi solitudinem faciunt, pacem appellant.",
    "translation_text": "They plunder, slaughter and seize, call it empire by false names, and where they make a wasteland they call it peace.",
    "original_source_name": "Perseus — Furneaux Latin edition",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0084%3Achapter%3D30%3Asection%3D6",
    "translation_source_name": "Perseus — Church & Brodribb translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0081%3Achapter%3D30",
    "translation_credit": "Scriptorium working translation checked against Church & Brodribb.",
    "context_hint": "A Roman historian composes a speech for a British leader. It is not a transcript.",
    "language_hint": "The triad of infinitives and antithesis are rhetorical construction.",
    "analytic_hint": "Excellent evidence for Tacitean critique; much weaker as verbatim Caledonian opinion.",
    "scaffold": [
      "Whose voice is mediated?",
      "What literary function does the speech serve?",
      "Which claim is about Tacitus rather than Calgacus?"
    ],
    "tags": [
      "imperialism",
      "speech",
      "Tacitus",
      "rhetoric"
    ],
    "recommended_modules": [
      "m05",
      "m07",
      "m09",
      "m11",
      "m16",
      "m17",
      "m21"
    ]
  },
  {
    "id": "tac_ann_1_1",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "lat",
    "title": "Tacitus on writing imperial history",
    "author": "Tacitus",
    "canonical_ref": "Tac. Ann. 1.1",
    "period": "early 2nd c. AD",
    "place": "Rome",
    "original_text": "urbem Romam a principio reges habuere ... Tiberii Gaique et Claudii ac Neronis res ... ob metum falsae, postquam occiderant recentibus odiis compositae sunt.",
    "translation_text": "Tacitus claims that accounts of living emperors were distorted by fear and posthumous accounts by recent hatred.",
    "original_source_name": "Perseus — Latin focus for Annals 1.1",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Tac.+Ann.+1.1&redirect=true",
    "translation_source_name": "Perseus — Church & Brodribb translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0078",
    "translation_credit": "Scriptorium working translation checked against Perseus English.",
    "context_hint": "Authorial program statement about bias in historical writing.",
    "language_hint": "Tacitus frames competing distortions before claiming his own stance.",
    "analytic_hint": "An author's claim to impartiality is itself evidence to evaluate, not a guarantee.",
    "scaffold": [
      "Which biases does Tacitus identify?",
      "How does he position himself?",
      "How would you test his claim of distance?"
    ],
    "tags": [
      "historiography",
      "bias",
      "Tacitus",
      "authorial-position"
    ],
    "recommended_modules": [
      "m05",
      "m06",
      "m07",
      "m09",
      "m11",
      "m17",
      "m21"
    ]
  },
  {
    "id": "sall_cat_10",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "lat",
    "title": "Sallust's moral explanation of Roman decline",
    "author": "Sallust",
    "canonical_ref": "Sall. Cat. 10.1–3",
    "period": "1st c. BC",
    "place": "Rome",
    "original_text": "sed ubi labore atque iustitia res publica crevit ... igitur primo pecuniae, deinde imperi cupido crevit.",
    "translation_text": "Sallust says that after Roman power grew, desire first for money and then for command increased.",
    "original_source_name": "Perseus — Ahlberg Latin edition",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0002%3Atext%3DCat.%3Achapter%3D10",
    "translation_source_name": "Perseus — Watson English translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0124",
    "translation_credit": "Scriptorium working translation checked against public-domain Perseus translation.",
    "context_hint": "Moralising historiography offers a causal narrative of decline.",
    "language_hint": "Abstract moral nouns do explanatory work; they are not directly measured variables.",
    "analytic_hint": "Turn the moral narrative into testable mechanisms before accepting it as causal explanation.",
    "scaffold": [
      "What causes are proposed?",
      "What evidence could operationalise them?",
      "Which rival explanation competes?"
    ],
    "tags": [
      "decline",
      "causality",
      "morality",
      "historiography"
    ],
    "recommended_modules": [
      "m03",
      "m07",
      "m09",
      "m11",
      "m12",
      "m17",
      "m21"
    ]
  },
  {
    "id": "suet_aug_28",
    "primary": true,
    "ready": true,
    "source_type": "biography",
    "language": "lat",
    "title": "Suetonius on Augustus and restoring the Republic",
    "author": "Suetonius",
    "canonical_ref": "Suet. Aug. 28",
    "period": "early 2nd c. AD",
    "place": "Rome",
    "original_text": "de reddenda re p. bis cogitavit ... sed reputans et se privatum non sine periculo fore ... retinuit.",
    "translation_text": "Suetonius says Augustus twice considered restoring the Republic but retained control after weighing danger to himself and the state.",
    "original_source_name": "Perseus — Suetonius, Divus Augustus",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Suet.+Aug.+28",
    "translation_source_name": "Perseus — Alexander Thomson translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Suet.+Aug.+28",
    "translation_credit": "Scriptorium working translation checked against Thomson.",
    "context_hint": "Imperial biography written more than a century after the constitutional settlement.",
    "language_hint": "Reported intentions are mediated by biographical tradition.",
    "analytic_hint": "Distinguish evidence for later memory of Augustus from direct evidence for his private motives.",
    "scaffold": [
      "What is action?",
      "What is reported intention?",
      "What chronological distance matters?",
      "What contemporary source could compare?"
    ],
    "tags": [
      "biography",
      "Augustus",
      "Republic",
      "motives"
    ],
    "recommended_modules": [
      "m05",
      "m10",
      "m11",
      "m12",
      "m17",
      "m21"
    ]
  }
];
