window.V6_AUTHENTIC_SOURCES = [
  {
    "id": "aio_salamis_1672",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Decree about the Athenian cleruchy on Salamis",
    "author": "Athenian People",
    "canonical_ref": "AIO 1672 = IG I³ 1 = ML 14",
    "period": "508–500 BC?",
    "place": "Athens / Salamis",
    "original_text": "ἔδοχσεν το͂ι δέμοι· τ̣[ὸς ἐΣ]αλαμ̣[ῖνι κλερόχ]ος οἰκε͂ν ἐᾶ Σαλαμῖνι ... Ἀθένεσι τελε͂ν καὶ στρατ[εύεσθ]αι ...",
    "translation_text": "The People decided: those holding allotments on Salamis are to be allowed to reside there ... at Athens they are to pay taxes and perform military service.",
    "original_source_name": "Attic Inscriptions Online — Greek text, AIO 1672",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIO/1672?text_type=greek",
    "translation_source_name": "AIO translated text — Stephen Lambert & Julian Schneider",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIO/1672",
    "translation_credit": "Scriptorium working translation checked against AIO.",
    "context_hint": "Public decree; fragmentary inscription. Brackets and dots signal editorial restoration or loss.",
    "language_hint": "Treat restored letters differently from preserved letters.",
    "analytic_hint": "Separate what the decree prescribes from what people demonstrably did.",
    "scaffold": [
      "What is preserved?",
      "What is restored?",
      "What is normative?",
      "What would require another source type?"
    ],
    "tags": [
      "decree",
      "law",
      "citizenship",
      "taxation",
      "military",
      "epigraphy"
    ],
    "recommended_modules": [
      "m03",
      "m04",
      "m05",
      "m08",
      "m10",
      "m11",
      "m17",
      "m18",
      "m21"
    ]
  },
  {
    "id": "thuc_2_37",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "grc",
    "title": "Funeral Oration: democracy and equality",
    "author": "Thucydides",
    "canonical_ref": "Thuc. 2.37.1",
    "period": "late 5th c. BC",
    "place": "Athens",
    "original_text": "καὶ ὄνομα μὲν διὰ τὸ μὴ ἐς ὀλίγους ἀλλ’ ἐς πλείονας οἰκεῖν δημοκρατία κέκληται· μέτεστι δὲ κατὰ μὲν τοὺς νόμους ... πᾶσι τὸ ἴσον.",
    "translation_text": "It is called a democracy because administration is in the hands of the many rather than the few; under the laws, equality is available to all in private disputes.",
    "original_source_name": "Perseus/Scaife — Greek edition of Thucydides",
    "original_source_url": "https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0003.tlg001.perseus-grc2:2.37.1/",
    "translation_source_name": "Perseus — Richard Crawley, 1910",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0200%3Abook%3D2%3Achapter%3D37%3Asection%3D1",
    "translation_credit": "Scriptorium working translation checked against Crawley.",
    "context_hint": "Thucydides presents Pericles' funeral speech; rhetorical setting and authorial mediation are central.",
    "language_hint": "δημοκρατία and τὸ ἴσον are analytically loaded terms, not transparent measurements.",
    "analytic_hint": "Do not equate political self-description with an exhaustive institutional description.",
    "scaffold": [
      "Who is speaking?",
      "For what audience?",
      "What is normative praise?",
      "What independent evidence could test the claims?"
    ],
    "tags": [
      "democracy",
      "rhetoric",
      "politics",
      "literary",
      "representation"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m06",
      "m07",
      "m09",
      "m11",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "herodotus_5_78",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "grc",
    "title": "Herodotus on isēgoriē and Athenian power",
    "author": "Herodotus",
    "canonical_ref": "Hdt. 5.78",
    "period": "5th c. BC",
    "place": "Athens",
    "original_text": "δηλοῖ δὲ ... ἡ ἰσηγορίη ὡς ἔστι χρῆμα σπουδαῖον ... ἀπαλλαχθέντες δὲ τυράννων μακρῷ πρῶτοι ἐγένοντο.",
    "translation_text": "It is evident that equality of political speech is a powerful thing: after the Athenians were rid of tyrants, they became markedly pre-eminent.",
    "original_source_name": "Perseus — Greek text of Herodotus",
    "original_source_url": "https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0016.tlg001.perseus-grc2:5.78/",
    "translation_source_name": "G. C. Macaulay translation, 1890",
    "translation_source_url": "https://lexundria.com/hdt/5.78/mcly",
    "translation_credit": "Scriptorium working translation checked against Macaulay.",
    "context_hint": "Narrative explanation written after the events; the passage explicitly links political regime and military performance.",
    "language_hint": "ἰσηγορίη is a contested political term; do not silently equate it with a complete modern model of democracy.",
    "analytic_hint": "The passage contains a causal claim. Ask what alternative mechanisms could produce the same observed outcome.",
    "scaffold": [
      "What is the observed change?",
      "What cause does Herodotus propose?",
      "What evidence is missing?",
      "What rival explanation would you test?"
    ],
    "tags": [
      "causality",
      "democracy",
      "tyranny",
      "military",
      "literary"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m09",
      "m11",
      "m12",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "caesar_bg_1_1",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "lat",
    "title": "Caesar's opening ethnography of Gaul",
    "author": "Julius Caesar",
    "canonical_ref": "Caes. BG 1.1",
    "period": "mid-1st c. BC",
    "place": "Gaul",
    "original_text": "Gallia est omnis divisa in partes tres ... Hi omnes lingua, institutis, legibus inter se differunt.",
    "translation_text": "Gaul as a whole is divided into three parts ... these peoples differ from one another in language, customs and laws.",
    "original_source_name": "Perseus — T. Rice Holmes Latin edition, 1914",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0002%3Abook%3D1%3Achapter%3D1",
    "translation_source_name": "W. A. McDevitte & W. S. Bohn translation, 1869",
    "translation_source_url": "https://atlas.perseus.tufts.edu/library/urn%3Acts%3AlatinLit%3Aphi0448.phi001.perseus-eng2/",
    "translation_credit": "Scriptorium working translation checked against McDevitte & Bohn.",
    "context_hint": "A commander-author classifies peoples at the opening of a conquest narrative.",
    "language_hint": "Notice categorical verbs and group labels. They create analytical units before evidence is presented.",
    "analytic_hint": "Treat Caesar's ethnographic categories as claims requiring testing, not neutral dataset labels.",
    "scaffold": [
      "Who creates the categories?",
      "What function do they serve?",
      "Could local variation disappear?",
      "What source could test them?"
    ],
    "tags": [
      "ethnography",
      "categories",
      "empire",
      "literary",
      "representation"
    ],
    "recommended_modules": [
      "m03",
      "m04",
      "m05",
      "m07",
      "m09",
      "m11",
      "m14",
      "m17",
      "m22"
    ]
  },
  {
    "id": "cicero_cat_1_1",
    "primary": true,
    "ready": true,
    "source_type": "speech",
    "language": "lat",
    "title": "Cicero's opening attack on Catiline",
    "author": "Cicero",
    "canonical_ref": "Cic. Cat. 1.1",
    "period": "63 BC",
    "place": "Rome",
    "original_text": "Quo usque tandem abutere, Catilina, patientia nostra? Quam diu etiam furor iste tuus nos eludet? Quem ad finem sese effrenata iactabit audacia?",
    "translation_text": "How long, Catiline, will you continue to abuse our patience? How much longer will that madness of yours evade us? How far will your unrestrained audacity go?",
    "original_source_name": "Perseus — A. C. Clark Latin edition, 1908",
    "original_source_url": "https://atlas.perseus.tufts.edu/library/urn%3Acts%3AlatinLit%3Aphi0474.phi013.perseus-lat2/",
    "translation_source_name": "C. D. Yonge translation, 1856",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0019%3Atext%3DCatil.%3Aspeech%3D1%3Achapter%3D1",
    "translation_credit": "Scriptorium working translation checked against Yonge.",
    "context_hint": "A highly adversarial senatorial speech. Accusation, persuasion and performance shape the evidence.",
    "language_hint": "The repeated rhetorical questions and loaded nouns are argumentative devices.",
    "analytic_hint": "A speech can reveal political strategies and categories even where it cannot independently establish every alleged fact.",
    "scaffold": [
      "Which statements are accusation?",
      "Which are observable circumstances?",
      "Who is the audience?",
      "What would corroboration look like?"
    ],
    "tags": [
      "rhetoric",
      "politics",
      "elite",
      "speech",
      "bias"
    ],
    "recommended_modules": [
      "m05",
      "m06",
      "m07",
      "m09",
      "m11",
      "m16",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "pliny_ep_10_96",
    "primary": true,
    "ready": true,
    "source_type": "letter",
    "language": "lat",
    "title": "Pliny asks Trajan how to handle Christians",
    "author": "Pliny the Younger",
    "canonical_ref": "Plin. Ep. 10.96.1",
    "period": "c. AD 112",
    "place": "Bithynia-Pontus",
    "original_text": "Sollemne est mihi, domine, omnia de quibus dubito ad te referre ... Cognitionibus de Christianis interfui numquam: ideo nescio quid et quatenus aut puniri soleat aut quaeri.",
    "translation_text": "It is my regular practice, lord, to refer to you everything about which I am uncertain ... I have never attended investigations of Christians, so I do not know what is usually punished or investigated, or to what extent.",
    "original_source_name": "Perseus — Latin text of Pliny, Epistles 10.96",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Plin.+Ep.+10.96",
    "translation_source_name": "Perseus/Scaife English translation record for Pliny's Letters",
    "translation_source_url": "https://scaife.perseus.org/",
    "translation_credit": "Scriptorium working translation from the Latin; external translation link for checking.",
    "context_hint": "Official correspondence from a provincial governor to the emperor. It records uncertainty and administrative decision-making.",
    "language_hint": "Pliny explicitly marks his uncertainty with dubito, nescio and questions about procedure.",
    "analytic_hint": "This is strong evidence for Pliny's problem and procedure, but not automatically for the prevalence or beliefs of all Christians.",
    "scaffold": [
      "What does Pliny know?",
      "What does he admit he does not know?",
      "What is administrative practice?",
      "What is evidence about Christians themselves?"
    ],
    "tags": [
      "letter",
      "governance",
      "religion",
      "procedure",
      "uncertainty",
      "province"
    ],
    "recommended_modules": [
      "m05",
      "m08",
      "m10",
      "m11",
      "m13",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "rgda_34",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "lat",
    "title": "Augustus on the constitutional settlement",
    "author": "Augustus",
    "canonical_ref": "Res Gestae 34",
    "period": "text completed by AD 14",
    "place": "Rome / Ankara copy",
    "original_text": "Post id tempus auctoritate omnibus praestiti, potestatis autem nihilo amplius habui quam ceteri qui mihi quoque in magistratu conlegae fuerunt.",
    "translation_text": "After that time I surpassed everyone in authority, but I possessed no more formal power than the others who were my colleagues in each magistracy.",
    "original_source_name": "Perseus — Latin text, Res Gestae 34",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=urn%3Acts%3AlatinLit%3Aphi1221.phi007.perseus-lat1%3A34",
    "translation_source_name": "LacusCurtius — F. W. Shipley, Loeb 1924 (public-domain text)",
    "translation_source_url": "https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Augustus/Res_Gestae/home.html",
    "translation_credit": "Scriptorium working translation checked against Shipley.",
    "context_hint": "Programmatic first-person political self-representation, preserved epigraphically in the provinces.",
    "language_hint": "Distinguish auctoritas from potestas; the contrast is part of Augustus' claim.",
    "analytic_hint": "Do not convert constitutional self-description into a neutral description of actual power.",
    "scaffold": [
      "What distinction does Augustus construct?",
      "Who benefits from this framing?",
      "What evidence could test de facto power?",
      "Why does epigraphic display matter?"
    ],
    "tags": [
      "princeps",
      "power",
      "self-representation",
      "inscription",
      "constitution"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m07",
      "m09",
      "m10",
      "m11",
      "m12",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "rib_1065_regina",
    "primary": true,
    "ready": true,
    "source_type": "funerary_inscription",
    "language": "lat",
    "title": "Funerary inscription for Regina",
    "author": "Barates (dedicator)",
    "canonical_ref": "RIB 1065",
    "period": "2nd century AD",
    "place": "Arbeia / South Shields",
    "original_text": "D(is) M(anibus) Regina liberta et coniuge Barates Palmyrenus natione Catuallauna an(norum) XXX",
    "translation_text": "To the spirits of the departed, and to Regina, his freedwoman and wife, a Catuvellaunian by origin, aged thirty: Barates of Palmyra set this up.",
    "original_source_name": "Roman Inscriptions of Britain — RIB 1065",
    "original_source_url": "https://romaninscriptionsofbritain.org/inscriptions/1065",
    "translation_source_name": "Roman Inscriptions of Britain — translation",
    "translation_source_url": "https://romaninscriptionsofbritain.org/inscriptions/1065",
    "translation_credit": "Scriptorium working rendering checked against RIB.",
    "context_hint": "Bilingual funerary monument; RIB also records a Palmyrene text. Commemoration is selective social representation.",
    "language_hint": "Abbreviations such as D.M. and ann. are formulaic. Grammatical irregularity itself may be historically meaningful.",
    "analytic_hint": "Do not infer a complete household biography from what the commemorator chose to inscribe.",
    "scaffold": [
      "Who commemorates whom?",
      "Which identities are named?",
      "Which are omitted?",
      "What does bilingualism allow you to ask?"
    ],
    "tags": [
      "funerary",
      "migration",
      "freedwoman",
      "identity",
      "bilingualism",
      "epigraphy"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m14",
      "m17",
      "m21",
      "m22"
    ]
  },
  {
    "id": "vindolanda_291",
    "primary": true,
    "ready": true,
    "source_type": "writing_tablet",
    "language": "lat",
    "title": "Birthday invitation from Claudia Severa to Sulpicia Lepidina",
    "author": "Claudia Severa",
    "canonical_ref": "Tab. Vindol. 291",
    "period": "c. AD 100",
    "place": "Vindolanda",
    "original_text": "Cl(audia) Seuerá Lepidinae suae salutem. iii Idus Septembres, soror, ad diem sollemnem natalem meum rogo libenter facias ut uenias ad nos ...",
    "translation_text": "Claudia Severa sends greetings to her Lepidina. Sister, on 11 September, for the celebration of my birthday, I warmly ask you to make sure that you come to us ...",
    "original_source_name": "Roman Inscriptions of Britain — TabVindol 291",
    "original_source_url": "https://romaninscriptionsofbritain.org/inscriptions/TabVindol291",
    "translation_source_name": "Roman Inscriptions of Britain — translation",
    "translation_source_url": "https://romaninscriptionsofbritain.org/inscriptions/TabVindol291",
    "translation_credit": "Scriptorium working translation checked against RIB.",
    "context_hint": "Private wooden writing tablet from the military frontier; a rare documentary glimpse of elite women's social networks.",
    "language_hint": "Epistolary formulae and spelling should be distinguished from analytical content.",
    "analytic_hint": "Exceptional preservation makes the source valuable but not automatically representative.",
    "scaffold": [
      "What relationship is directly attested?",
      "What social practices are only implied?",
      "Why was this preserved?",
      "What comparison would test representativeness?"
    ],
    "tags": [
      "letter",
      "women",
      "frontier",
      "social-network",
      "documentary",
      "material"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m14",
      "m17",
      "m21",
      "m22"
    ]
  },
  {
    "id": "poxy_4_744",
    "primary": true,
    "ready": true,
    "source_type": "papyrus_letter",
    "language": "grc",
    "title": "Hilarion to Alis",
    "author": "Hilarion",
    "canonical_ref": "P.Oxy. IV 744",
    "period": "1 BC",
    "place": "Oxyrhynchus / Alexandria",
    "original_text": "ἐρωτῶ σε καὶ παρακαλῶ σε ἐπιμελήθι τῷ παιδίῳ ... ἐὰν ἦν ἄρσενον ἄφες, ἐὰν ἦν θήλεα ἔκβαλε.",
    "translation_text": "I ask and urge you to take care of the child ... if it is male, let it remain; if it is female, expose it.",
    "original_source_name": "DDbDP transcription, P.Oxy. IV 744",
    "original_source_url": "https://papyri.info/ddbdp/p.oxy;4;744",
    "translation_source_name": "Select Papyri 1.105 / Attalus",
    "translation_source_url": "https://www.attalus.org/docs/select1/p105.html",
    "translation_credit": "Scriptorium working translation checked against the published English selection.",
    "context_hint": "Private letter, not a legal prescription or population-level dataset. Its documentary immediacy does not erase individual context.",
    "language_hint": "The papyrus preserves non-classical spellings and grammar; editorial normalization can conceal historically useful linguistic evidence.",
    "analytic_hint": "One shocking instruction cannot by itself establish prevalence, normality or legal status of a practice.",
    "scaffold": [
      "What is directly instructed?",
      "What broader practice is not demonstrated?",
      "What comparison is required?",
      "Which kind of conclusion is proportionate?"
    ],
    "tags": [
      "papyrus",
      "letter",
      "family",
      "gender",
      "documentary",
      "representativeness"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m17",
      "m21",
      "m22"
    ]
  },
  {
    "id": "ocre_aug_86a",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Augustus denarius: SIGNIS RECEPTIS",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 86A",
    "period": "19–15 BC",
    "place": "Colonia Patricia",
    "original_text": "Obverse legend: CAESAR AVGVSTVS. Reverse legend: SIGNIS RECEPTIS. Reverse type: shield marked CL V, flanked by an aquila and a military standard.",
    "translation_text": "Object data rather than a translated text: the reverse publicly evokes the recovery of military standards and the clipeus virtutis.",
    "original_source_name": "Online Coins of the Roman Empire — RIC I² Augustus 86A",
    "original_source_url": "http://numismatics.org/ocre/id/ric.1(2).aug.86A",
    "translation_source_name": "OCRE object/legend record",
    "translation_source_url": "http://numismatics.org/ocre/id/ric.1(2).aug.86A",
    "translation_credit": "No literary translation: Scriptorium preserves the legend and object description; interpretation must be argued.",
    "context_hint": "Minted object with official iconographic and textual choices; circulation is not the same thing as proven audience reception.",
    "language_hint": "Expand AVGVSTVS and SIGNIS RECEPTIS, but keep expansion separate from historical interpretation.",
    "analytic_hint": "Coin imagery is excellent evidence for messages made available in circulation, weaker evidence for what every viewer believed.",
    "scaffold": [
      "What is physically on the coin?",
      "What is iconographic interpretation?",
      "Who issued it?",
      "How would circulation/reception be tested?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "Augustus",
      "military",
      "iconography",
      "reception"
    ],
    "recommended_modules": [
      "m03",
      "m04",
      "m05",
      "m10",
      "m11",
      "m14",
      "m17",
      "m21",
      "m22"
    ]
  },
  {
    "id": "aio_aiuk2_8",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "List of Athenians and Romans",
    "author": "Unknown civic/associational context",
    "canonical_ref": "AIUK 2 no. 8 = IG II² 2460",
    "period": "c. 100–90 BC",
    "place": "Athens",
    "original_text": "Ἀλκέτου τοῦ Εὐαγίωνος Περιθοίδου ... Λευκίου τοῦ Λευκίου ῾Ρωμαίου Μαάρκου τοῦ Μαάρκου ῾Ρωμαίου ...",
    "translation_text": "The list names Athenians by deme and also Lucius son of Lucius and Marcus son of Marcus, identified as Romans.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIUK2/8?text_type=greek",
    "translation_source_name": "AIO translation by Stephen Lambert",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIUK2/8",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "A list without its lost wider context. Prosopography can suggest networks, but the original purpose is uncertain.",
    "language_hint": "Ethnics/demotics identify civic affiliations; names alone do not establish social role.",
    "analytic_hint": "Do not infer a complete Roman community from two Roman names in one fragmentary list.",
    "scaffold": [
      "What is directly listed?",
      "What context is missing?",
      "Which prosopographic inference is defensible?",
      "What comparison would test significance?"
    ],
    "tags": [
      "prosopography",
      "Romans",
      "Athens",
      "list",
      "identity"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m14",
      "m21"
    ]
  },
  {
    "id": "aio_ro22",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Second Athenian League decree",
    "author": "Athenian Council and People",
    "canonical_ref": "RO 22 = IG II² 43",
    "period": "378/7 BC",
    "place": "Athens",
    "original_text": "ἔδοξεν τῆι βολῆι καὶ τῶι δήμωι ... ἐλευθέρους καὶ αὐτονόμους ... μήτε φρουρὰν ... μήτε φόρον φέροντι ...",
    "translation_text": "The decree presents prospective allies as free and autonomous, without an Athenian garrison, governor, or tribute.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/RO/22?text_type=greek",
    "translation_source_name": "AIO translation by Stephen Lambert & P. J. Rhodes",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/RO/22",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "Alliance decree deliberately defines acceptable interstate relations after memories of fifth-century Athenian empire.",
    "language_hint": "ἐλευθερία, αὐτονομία and φόρος are politically charged terms.",
    "analytic_hint": "Treat promises in an alliance decree as normative commitments, then test later practice separately.",
    "scaffold": [
      "What commitments are explicit?",
      "What historical memory may shape them?",
      "What later evidence could test compliance?"
    ],
    "tags": [
      "alliance",
      "autonomy",
      "empire",
      "decree",
      "norm-practice"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m07",
      "m10",
      "m11",
      "m12",
      "m17",
      "m21"
    ]
  },
  {
    "id": "aio_aiuk9_pan",
    "primary": true,
    "ready": true,
    "source_type": "dedication",
    "language": "grc",
    "title": "Dedication to Pan and the Nymphs",
    "author": "Private dedicator from Phlya",
    "canonical_ref": "AIUK 9 Appendix 1 = IG II³ 4, 1430",
    "period": "c. 350–330 BC",
    "place": "Attica",
    "original_text": "[- - - - - - ί]π̣πο Φλυεὺς ἀνέθηκεν.",
    "translation_text": "A man of Phlya, whose name is partly lost, dedicated the object.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIUK9/appendix-1?text_type=greek",
    "translation_source_name": "AIO translation by Peter Liddel & Polly Low",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIUK9/appendix-1",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "The inscribed relief survives through an early modern depiction; object, image and text have different transmission histories.",
    "language_hint": "ἀνέθηκεν marks dedication; the lost name limits social identification.",
    "analytic_hint": "Material context and survival history are part of source criticism, not decoration.",
    "scaffold": [
      "What survives physically?",
      "What survives only through a drawing?",
      "What can the demotic tell you?"
    ],
    "tags": [
      "dedication",
      "religion",
      "relief",
      "material-culture",
      "transmission"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m21"
    ]
  },
  {
    "id": "aio_igi3_246",
    "primary": true,
    "ready": true,
    "source_type": "sacrificial_calendar",
    "language": "grc",
    "title": "Sacrificial calendar",
    "author": "Local Attic community",
    "canonical_ref": "IG I³ 246 = AIUK 4.1 no. 2",
    "period": "470–450 BC",
    "place": "Attica",
    "original_text": "Πλυντερίοισι Ἀθεναίαι οἶν ... Hέρμει πυρῶν δύο χοίνικε ...",
    "translation_text": "At the Plynteria a sheep is assigned to Athena; another entry specifies two choenices of wheat for Hermes.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIUK41/2?text_type=greek",
    "translation_source_name": "AIO translation by Stephen Lambert & Feyo Schuddeboom",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIUK41/2",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "A fragmentary ritual calendar inscribed on multiple faces; its original findspot is unknown.",
    "language_hint": "Archaic orthography and damaged text complicate normalization.",
    "analytic_hint": "Prescribed offerings reveal institutional ritual provision, not automatically actual attendance or belief.",
    "scaffold": [
      "Which entries are certain?",
      "What does a calendar regulate?",
      "Which social practices remain invisible?"
    ],
    "tags": [
      "religion",
      "calendar",
      "ritual",
      "fragmentary",
      "epigraphy"
    ],
    "recommended_modules": [
      "m05",
      "m08",
      "m10",
      "m11",
      "m13",
      "m21"
    ]
  },
  {
    "id": "aio_802_chios",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Alliance with Chios",
    "author": "Athenian Council and People",
    "canonical_ref": "AIO 802",
    "period": "384/3 BC",
    "place": "Athens",
    "original_text": "συμμάχους ποιεῖσθαι Χίους ἐπ’ ἐλευθερίαι καὶ αὐτονομίαι ... βοηθεῖν ... παντὶ σθένει ...",
    "translation_text": "The Chians are to become allies on terms of freedom and autonomy, with mutual military assistance.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIO/802?text_type=greek",
    "translation_source_name": "Attic Inscriptions Online translated record",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIO/802",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "Formal alliance provisions encode an ideal interstate relationship.",
    "language_hint": "Pay attention to reciprocal conditional clauses and the formula κατὰ τὸ δυνατόν.",
    "analytic_hint": "Mutual obligation on stone is evidence for negotiated norms, not proof of later equal performance.",
    "scaffold": [
      "Which obligations are reciprocal?",
      "Where is discretion preserved?",
      "How could later behaviour be tested?"
    ],
    "tags": [
      "alliance",
      "autonomy",
      "diplomacy",
      "decree"
    ],
    "recommended_modules": [
      "m05",
      "m10",
      "m11",
      "m12",
      "m17",
      "m21"
    ]
  },
  {
    "id": "aio_807_dionysios",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Alliance with Dionysios I of Syracuse",
    "author": "Athenian People",
    "canonical_ref": "AIO 807",
    "period": "368/7 BC?",
    "place": "Athens",
    "original_text": "ἐπαινέσαι ... Διονύσιον ... σύμμαχον ... ἐάν τις ἴηι ἐπὶ τὴν χώραν ... βοηθεῖν ...",
    "translation_text": "The decree praises Dionysios and establishes mutual assistance if either party is attacked.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/AIO/807?text_type=greek",
    "translation_source_name": "Attic Inscriptions Online translated record",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/AIO/807",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "Diplomatic honorific language and treaty clauses coexist in one public text.",
    "language_hint": "Separate praise formulae from operative clauses.",
    "analytic_hint": "Different parts of one inscription can have different evidential status.",
    "scaffold": [
      "Which words praise?",
      "Which clauses create obligations?",
      "Which historical claim relies on which part?"
    ],
    "tags": [
      "diplomacy",
      "treaty",
      "ruler",
      "decree",
      "genre"
    ],
    "recommended_modules": [
      "m05",
      "m10",
      "m11",
      "m16",
      "m17",
      "m21"
    ]
  },
  {
    "id": "aio_or155_coinage",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Decree enforcing Athenian coins, weights and measures",
    "author": "Athenian authorities",
    "canonical_ref": "OR 155 = IG I³ 1453",
    "period": "c. 414 BC?",
    "place": "Athenian sphere",
    "original_text": "ἐάν τις κόπτηι νόμισμα ... καὶ μὴ χρῆται νομίσμασιν τοῖς Ἀθηναίων ἢ σταθμοῖς ἢ μέτροις ...",
    "translation_text": "The decree penalizes minting or using currency, weights, or measures contrary to the Athenian standards it prescribes.",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/IGI3/1453?text_type=greek",
    "translation_source_name": "Attic Inscriptions Online translated record",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/IGI3/1453",
    "translation_credit": "Scriptorium working translation; check against AIO.",
    "context_hint": "Highly fragmentary coercive regulation linked to Athenian economic standards.",
    "language_hint": "Editorial restorations materially affect how the regulatory mechanism is reconstructed.",
    "analytic_hint": "Enforcement provisions indicate state intention; actual monetary circulation needs numismatic evidence.",
    "scaffold": [
      "What is normatively required?",
      "Where is the text restored?",
      "What coin evidence could corroborate practice?"
    ],
    "tags": [
      "coinage",
      "weights",
      "measures",
      "empire",
      "economy",
      "law"
    ],
    "recommended_modules": [
      "m05",
      "m10",
      "m11",
      "m12",
      "m13",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_127",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Aureus: RIC I² Augustus 127",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 127",
    "period": "18–17 BC",
    "place": "Colonia Patricia",
    "original_text": "Legend: AVGVSTVS. Type: Capricorn holding globe with rudder; cornucopia above.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://www.numismatics.org/ocre/id/ric.1%282%29.aug.127",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://www.numismatics.org/ocre/id/ric.1%282%29.aug.127",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_253",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC I² Augustus 253",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 253",
    "period": "32–29 BC",
    "place": "uncertain Italian mint",
    "original_text": "Legend: CAESAR DIVI F. Type: Octavian in military dress, with spear.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.253",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.253",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_11a",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "As: RIC I² Augustus 11A",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 11A",
    "period": "25–23 BC",
    "place": "Caesaraugusta",
    "original_text": "Legend: P CARISIVS LEG AVGVSTI EMERITA. Type: City wall and gateway marked EMERITA.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.11A",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.11A",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_126",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC I² Augustus 126",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 126",
    "period": "18–17 BC",
    "place": "Colonia Patricia",
    "original_text": "Legend: AVGVSTVS. Type: Capricorn with globe, rudder and cornucopia.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.126",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.126",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_220",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC I² Augustus 220",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 220",
    "period": "AD 13–14",
    "place": "Lugdunum",
    "original_text": "Legend: PONTIF MAXIM. Type: Seated female figure holding branch and sceptre.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://www.numismatics.org/ocre/id/ric.1%282%29.aug.220",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://www.numismatics.org/ocre/id/ric.1%282%29.aug.220",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_160",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "As: RIC I² Augustus 160",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 160",
    "period": "AD 10–14",
    "place": "Nemausus",
    "original_text": "Legend: COL NEM. Type: Crocodile chained to palm; Augustus and Agrippa on obverse.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.160",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.160",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_aug_256",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC I² Augustus 256",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Augustus 256",
    "period": "32–29 BC",
    "place": "uncertain Italian mint",
    "original_text": "Legend: CAESAR DIVI F. Type: Victory bust; Neptune with globe, aplustre and spear.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.256",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.aug.256",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_tib_30",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC I² Tiberius 30",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Tiberius 30",
    "period": "AD 14–37",
    "place": "Lugdunum",
    "original_text": "Legend: PONTIF MAXIM. Type: Seated female figure with branch and sceptre.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.tib.30",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.tib.30",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_nero_101",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Sestertius: RIC I² Nero 101",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Nero 101",
    "period": "AD 62–68",
    "place": "Rome",
    "original_text": "Legend: CONG II DAT POP. Type: Imperial distribution scene with citizens, Minerva and Liberalitas.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.ner.101",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.ner.101",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_nero_269",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Sestertius: RIC I² Nero 269",
    "author": "Roman mint authority",
    "canonical_ref": "RIC I² Nero 269",
    "period": "AD 62–68",
    "place": "Rome",
    "original_text": "Legend: PACE P R TERRA MARIQ PARTA IANVM CLVSIT S C. Type: Temple of Janus with closed doors.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.ner.269",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1%282%29.ner.269",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "ocre_trajan_318",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "material",
    "title": "Denarius: RIC II Trajan 318",
    "author": "Roman mint authority",
    "canonical_ref": "RIC II Trajan 318",
    "period": "AD 114",
    "place": "Rome",
    "original_text": "Legend: P M TR P COS VI P P S P Q R FORT RED. Type: Fortuna with rudder and cornucopia.",
    "translation_text": "Object record: preserve the legend, denomination, mint, metal and iconographic type before interpreting the political message.",
    "original_source_name": "Online Coins of the Roman Empire (OCRE)",
    "original_source_url": "https://numismatics.org/ocre/id/ric.2.tr.318_denarius",
    "translation_source_name": "OCRE typological/object record",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.2.tr.318_denarius",
    "translation_credit": "No literary translation; Scriptorium uses OCRE object data.",
    "context_hint": "Mass-produced official object; minting and circulation are distinct from individual reception.",
    "language_hint": "Expand abbreviations only after recording the legend exactly.",
    "analytic_hint": "Treat imagery and legend as issued communication; audience response requires separate evidence.",
    "scaffold": [
      "What is physically encoded?",
      "What is an iconographic interpretation?",
      "What would circulation data add?"
    ],
    "tags": [
      "coin",
      "numismatics",
      "imperial-image",
      "circulation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m13",
      "m14",
      "m21"
    ]
  },
  {
    "id": "tac_agric_30_6",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "lat",
    "title": "Calgacus' speech on Roman imperialism",
    "author": "Tacitus",
    "canonical_ref": "Tac. Agr. 30.6",
    "period": "c. AD 98",
    "place": "Britain (narrative setting)",
    "original_text": "auferre trucidare rapere falsis nominibus imperium, atque ubi solitudinem faciunt, pacem appellant.",
    "translation_text": "They plunder, slaughter and seize, call it empire by false names, and where they make a wasteland they call it peace.",
    "original_source_name": "Perseus — Furneaux Latin edition",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0084%3Achapter%3D30%3Asection%3D6",
    "translation_source_name": "Perseus — Church & Brodribb translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0081%3Achapter%3D30",
    "translation_credit": "Scriptorium working translation checked against Church & Brodribb.",
    "context_hint": "A Roman historian composes a speech for a British leader. It is not a transcript.",
    "language_hint": "The triad of infinitives and antithesis are rhetorical construction.",
    "analytic_hint": "Excellent evidence for Tacitean critique; much weaker as verbatim Caledonian opinion.",
    "scaffold": [
      "Whose voice is mediated?",
      "What literary function does the speech serve?",
      "Which claim is about Tacitus rather than Calgacus?"
    ],
    "tags": [
      "imperialism",
      "speech",
      "Tacitus",
      "rhetoric"
    ],
    "recommended_modules": [
      "m05",
      "m07",
      "m09",
      "m11",
      "m16",
      "m17",
      "m21"
    ]
  },
  {
    "id": "tac_ann_1_1",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "lat",
    "title": "Tacitus on writing imperial history",
    "author": "Tacitus",
    "canonical_ref": "Tac. Ann. 1.1",
    "period": "early 2nd c. AD",
    "place": "Rome",
    "original_text": "urbem Romam a principio reges habuere ... Tiberii Gaique et Claudii ac Neronis res ... ob metum falsae, postquam occiderant recentibus odiis compositae sunt.",
    "translation_text": "Tacitus claims that accounts of living emperors were distorted by fear and posthumous accounts by recent hatred.",
    "original_source_name": "Perseus — Latin focus for Annals 1.1",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Tac.+Ann.+1.1&redirect=true",
    "translation_source_name": "Perseus — Church & Brodribb translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0078",
    "translation_credit": "Scriptorium working translation checked against Perseus English.",
    "context_hint": "Authorial program statement about bias in historical writing.",
    "language_hint": "Tacitus frames competing distortions before claiming his own stance.",
    "analytic_hint": "An author's claim to impartiality is itself evidence to evaluate, not a guarantee.",
    "scaffold": [
      "Which biases does Tacitus identify?",
      "How does he position himself?",
      "How would you test his claim of distance?"
    ],
    "tags": [
      "historiography",
      "bias",
      "Tacitus",
      "authorial-position"
    ],
    "recommended_modules": [
      "m05",
      "m06",
      "m07",
      "m09",
      "m11",
      "m17",
      "m21"
    ]
  },
  {
    "id": "sall_cat_10",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "lat",
    "title": "Sallust's moral explanation of Roman decline",
    "author": "Sallust",
    "canonical_ref": "Sall. Cat. 10.1–3",
    "period": "1st c. BC",
    "place": "Rome",
    "original_text": "sed ubi labore atque iustitia res publica crevit ... igitur primo pecuniae, deinde imperi cupido crevit.",
    "translation_text": "Sallust says that after Roman power grew, desire first for money and then for command increased.",
    "original_source_name": "Perseus — Ahlberg Latin edition",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0002%3Atext%3DCat.%3Achapter%3D10",
    "translation_source_name": "Perseus — Watson English translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0124",
    "translation_credit": "Scriptorium working translation checked against public-domain Perseus translation.",
    "context_hint": "Moralising historiography offers a causal narrative of decline.",
    "language_hint": "Abstract moral nouns do explanatory work; they are not directly measured variables.",
    "analytic_hint": "Turn the moral narrative into testable mechanisms before accepting it as causal explanation.",
    "scaffold": [
      "What causes are proposed?",
      "What evidence could operationalise them?",
      "Which rival explanation competes?"
    ],
    "tags": [
      "decline",
      "causality",
      "morality",
      "historiography"
    ],
    "recommended_modules": [
      "m03",
      "m07",
      "m09",
      "m11",
      "m12",
      "m17",
      "m21"
    ]
  },
  {
    "id": "suet_aug_28",
    "primary": true,
    "ready": true,
    "source_type": "biography",
    "language": "lat",
    "title": "Suetonius on Augustus and restoring the Republic",
    "author": "Suetonius",
    "canonical_ref": "Suet. Aug. 28",
    "period": "early 2nd c. AD",
    "place": "Rome",
    "original_text": "de reddenda re p. bis cogitavit ... sed reputans et se privatum non sine periculo fore ... retinuit.",
    "translation_text": "Suetonius says Augustus twice considered restoring the Republic but retained control after weighing danger to himself and the state.",
    "original_source_name": "Perseus — Suetonius, Divus Augustus",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Suet.+Aug.+28",
    "translation_source_name": "Perseus — Alexander Thomson translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Suet.+Aug.+28",
    "translation_credit": "Scriptorium working translation checked against Thomson.",
    "context_hint": "Imperial biography written more than a century after the constitutional settlement.",
    "language_hint": "Reported intentions are mediated by biographical tradition.",
    "analytic_hint": "Distinguish evidence for later memory of Augustus from direct evidence for his private motives.",
    "scaffold": [
      "What is action?",
      "What is reported intention?",
      "What chronological distance matters?",
      "What contemporary source could compare?"
    ],
    "tags": [
      "biography",
      "Augustus",
      "Republic",
      "motives"
    ],
    "recommended_modules": [
      "m05",
      "m10",
      "m11",
      "m12",
      "m17",
      "m21"
    ]
  },
  {
    "id": "arist_athpol_42_1",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "grc",
    "title": "Citizenship and age-class organization",
    "author": "Aristotle",
    "canonical_ref": "Aristot. Ath. Pol. 42.1",
    "period": "4th c. BC",
    "place": "Athens",
    "original_text": "μετέχει δὲ τῆς πολιτείας τοὺς ἐξ ἀμφοῖν γεγονότας ἀστῶν· ἐγγράφονται δ' εἰς τοὺς δημότας ὀκτωκαιδεκαετεῖς γεγονότες.",
    "translation_text": "Those born from two citizen parents share in the constitution; they are enrolled among the demesmen when they have reached the age of eighteen.",
    "original_source_name": "Perseus Digital Library — Greek text",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Aristot.+Ath.+Pol.+42.1",
    "translation_source_name": "Perseus Digital Library — English translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Aristot.+Ath.+Pol.+42.1&fromdoc=Perseus:text:1999.01.0046",
    "translation_credit": "Scriptorium working translation checked against Perseus.",
    "context_hint": "Institutional description; consider whether Aristotle describes norm, practice, or an idealized system.",
    "language_hint": "Politeia can mean constitution/order of the state, not simply “politics”.",
    "analytic_hint": "Good for operationalizing citizenship, but insufficient for lived civic practice on its own.",
    "scaffold": [
      "What is the formal rule?",
      "What remains unknown about actual practice?",
      "Which complementary source type could test practice?"
    ],
    "tags": [
      "citizenship",
      "constitution",
      "democracy",
      "law",
      "norm-practice",
      "governance"
    ],
    "recommended_modules": [
      "m02",
      "m03",
      "m04",
      "m05",
      "m10",
      "m11",
      "m20"
    ]
  },
  {
    "id": "demosthenes_24_20",
    "primary": true,
    "ready": true,
    "source_type": "speech",
    "language": "grc",
    "title": "Why laws and decrees must be distinguished",
    "author": "Demosthenes",
    "canonical_ref": "Dem. 24.20",
    "period": "4th c. BC",
    "place": "Athens",
    "original_text": "νόμος μὲν γάρ ἐστιν ὃ πάντας ὁμοίως δεῖ κυρίως ἔχειν, ψήφισμα δ' ὃ περὶ τῶν παρόντων ἐστίν.",
    "translation_text": "A law is something that must have authoritative force equally for all, whereas a decree concerns the matter at hand.",
    "original_source_name": "Perseus Digital Library — Greek text",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Dem.+24.20",
    "translation_source_name": "Perseus Digital Library — English translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Dem.+24.20&fromdoc=Perseus:text:1999.01.0073",
    "translation_credit": "Scriptorium working translation checked against Perseus.",
    "context_hint": "Forensic rhetoric within a specific case. The distinction is rhetorically useful but must still be contextualized.",
    "language_hint": "Nomos and psephisma are technical institutional terms.",
    "analytic_hint": "Excellent for method and concept work: formal categories are not yet evidence of consistent practice.",
    "scaffold": [
      "What distinction is being drawn?",
      "Why is that distinction useful for historians?",
      "Where might rhetoric exaggerate the clarity of the categories?"
    ],
    "tags": [
      "law",
      "decree",
      "procedure",
      "politics",
      "institutions",
      "norm-practice"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m08",
      "m11",
      "m14",
      "m21"
    ]
  },
  {
    "id": "xenophon_poroi_4_17",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "grc",
    "title": "Proposal to attract metics to Athens",
    "author": "Xenophon",
    "canonical_ref": "Xen. Vect. 4.17",
    "period": "4th c. BC",
    "place": "Athens",
    "original_text": "εἰ δὲ καὶ μετοίκοις θεραπεία τις προσγένοιτο, ἔμοιγε δοκεῖ πλείους τε ἂν ἐγγίγνεσθαι καὶ τὰς προσόδους αὐξήσεσθαι.",
    "translation_text": "If some additional consideration were granted also to metics, it seems to me that they would become more numerous and that the revenues would increase.",
    "original_source_name": "Perseus Digital Library — Greek text",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Xen.+Vect.+4.17",
    "translation_source_name": "Perseus Digital Library — English translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Xen.+Vect.+4.17&fromdoc=Perseus:text:1999.01.0210",
    "translation_credit": "Scriptorium working translation checked against Perseus.",
    "context_hint": "Programmatic proposal, not an administrative record of what Athens actually implemented.",
    "language_hint": "Prosodoi means revenues/income.",
    "analytic_hint": "Useful for separating policy proposal from evidence of economic reality.",
    "scaffold": [
      "Is this description or recommendation?",
      "What population is targeted?",
      "What source would show actual implementation?"
    ],
    "tags": [
      "economy",
      "migration",
      "taxation",
      "metics",
      "policy",
      "norm-practice"
    ],
    "recommended_modules": [
      "m01",
      "m02",
      "m04",
      "m08",
      "m10",
      "m17"
    ]
  },
  {
    "id": "lysias_12_4",
    "primary": true,
    "ready": true,
    "source_type": "speech",
    "language": "grc",
    "title": "The Thirty seize citizens without trial",
    "author": "Lysias",
    "canonical_ref": "Lys. 12.4",
    "period": "4th c. BC",
    "place": "Athens",
    "original_text": "οἱ δὲ τριάκοντα πολλοὺς μὲν ἄνευ δίκης ἀπέκτειναν, πολλοὺς δ' ἐξέβαλον τῆς πόλεως.",
    "translation_text": "The Thirty put many to death without trial and drove many others out of the city.",
    "original_source_name": "Perseus Digital Library — Greek text",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Lys.+12.4",
    "translation_source_name": "Perseus Digital Library — English translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Lys.+12.4&fromdoc=Perseus:text:1999.01.0158",
    "translation_credit": "Scriptorium working translation checked against Perseus.",
    "context_hint": "Court speech by an involved party. Strongly perspectival and therefore ideal for source criticism.",
    "language_hint": "Notice the compression and accusatory rhythm of the sentence.",
    "analytic_hint": "Important for debates on political violence, but numbers and generalization need corroboration.",
    "scaffold": [
      "What does the speaker want the jury to believe?",
      "Which part may still preserve a historical core?",
      "What corroboration would you need?"
    ],
    "tags": [
      "violence",
      "politics",
      "rhetoric",
      "trial",
      "tyranny",
      "representation"
    ],
    "recommended_modules": [
      "m05",
      "m06",
      "m10",
      "m11",
      "m17",
      "m22"
    ]
  },
  {
    "id": "andocides_1_81",
    "primary": true,
    "ready": true,
    "source_type": "speech",
    "language": "grc",
    "title": "The amnesty and civic reconciliation",
    "author": "Andocides",
    "canonical_ref": "Andoc. 1.81",
    "period": "4th c. BC",
    "place": "Athens",
    "original_text": "ὅρκους ὤμοσαν μὴ μνησικακήσειν ἀλλήλοις.",
    "translation_text": "They swore oaths not to remember past wrongs against one another.",
    "original_source_name": "Perseus Digital Library — Greek text",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Andoc.+1.81",
    "translation_source_name": "Perseus Digital Library — English translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Andoc.+1.81&fromdoc=Perseus:text:1999.01.0177",
    "translation_credit": "Scriptorium working translation checked against Perseus.",
    "context_hint": "A compressed formulation of amnesty logic. Normative promise and practical enforcement are separate questions.",
    "language_hint": "Mnēsikakein concerns “remembering wrongs / bearing grudges”.",
    "analytic_hint": "Useful for norm-versus-practice analysis and for defining political reconciliation.",
    "scaffold": [
      "What is the norm?",
      "What evidence would show compliance or failure?",
      "How limited is the phrase itself?"
    ],
    "tags": [
      "amnesty",
      "law",
      "politics",
      "reconciliation",
      "norm-practice"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m10",
      "m14",
      "m18"
    ]
  },
  {
    "id": "polyb_6_11_11",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "grc",
    "title": "The Roman constitution as mixed",
    "author": "Polybius",
    "canonical_ref": "Polyb. 6.11.11",
    "period": "2nd c. BC",
    "place": "Rome",
    "original_text": "ἐκ δὲ τούτων ἁπάντων ἐγένετο τὸ πολίτευμα μικτὸν καὶ κατὰ πάντα θαυμάσιον.",
    "translation_text": "From all these elements there resulted a mixed constitution, admirable in every respect.",
    "original_source_name": "Perseus Digital Library — Greek text",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Polyb.+6.11.11",
    "translation_source_name": "Perseus Digital Library — English translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Polyb.+6.11.11&fromdoc=Perseus:text:1999.01.0234",
    "translation_credit": "Scriptorium working translation checked against Perseus.",
    "context_hint": "Analytical model by a Greek historian explaining Roman success.",
    "language_hint": "Mixed constitution is an interpretive model, not a Roman self-description.",
    "analytic_hint": "Ideal for theory and model translation: descriptive power does not remove interpretive choices.",
    "scaffold": [
      "What model is Polybius using?",
      "How could you operationalize it historically?",
      "What would count as disconfirming evidence?"
    ],
    "tags": [
      "Republic",
      "constitution",
      "theory",
      "politics",
      "model",
      "Rome"
    ],
    "recommended_modules": [
      "m06",
      "m07",
      "m09",
      "m11",
      "m20",
      "m22"
    ]
  },
  {
    "id": "cicero_verr_2_3_163",
    "primary": true,
    "ready": true,
    "source_type": "speech",
    "language": "lat",
    "title": "Provincial grain exactions under Verres",
    "author": "Cicero",
    "canonical_ref": "Cic. Verr. 2.3.163",
    "period": "1st c. BC",
    "place": "Sicily / Rome",
    "original_text": "frumentum non modo imperatum, sed etiam ereptum atque ablatum esse dicunt.",
    "translation_text": "They say that grain was not merely requisitioned, but actually seized and carried off.",
    "original_source_name": "Perseus Digital Library — Latin text",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Cic.+Ver.+2.3.163",
    "translation_source_name": "Perseus Digital Library — English translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Cic.+Ver.+2.3.163&fromdoc=Perseus:text:1999.02.0018",
    "translation_credit": "Scriptorium working translation checked against Perseus.",
    "context_hint": "Accusatory oratory. Distinguish forensic amplification from possible administrative realities.",
    "language_hint": "Imperatum suggests official demand; ereptum implies violent seizure.",
    "analytic_hint": "Strong for analyzing rhetoric around governance and exploitation, weaker for exact quantification alone.",
    "scaffold": [
      "Which administrative practice is alleged?",
      "What rhetorical escalation is visible?",
      "What other evidence could test the claim?"
    ],
    "tags": [
      "economy",
      "province",
      "governance",
      "rhetoric",
      "taxation",
      "norm-practice"
    ],
    "recommended_modules": [
      "m05",
      "m08",
      "m10",
      "m11",
      "m17",
      "m22"
    ]
  },
  {
    "id": "res_gestae_34",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "lat",
    "title": "Augustus restores the Republic?",
    "author": "Augustus",
    "canonical_ref": "RGDA 34.1–3",
    "period": "AD 14 copy of earlier text",
    "place": "Ancyra / empire-wide circulation",
    "original_text": "post id tempus auctoritate omnibus praestiti, potestatis autem nihilo amplius habui quam ceteri qui mihi quoque in magistratu conlegae fuerunt.",
    "translation_text": "After that time I excelled all in influence, but I possessed no more official power than the others who were my colleagues in each magistracy.",
    "original_source_name": "LacusCurtius — Latin text of the Res Gestae",
    "original_source_url": "https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Augustus/Res_Gestae/34*.html",
    "translation_source_name": "LacusCurtius — English translation",
    "translation_source_url": "https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Augustus/Res_Gestae/34*.html",
    "translation_credit": "Scriptorium working translation checked against the standard English rendering on LacusCurtius.",
    "context_hint": "Official self-representation of rule. Separate constitutional language from political reality.",
    "language_hint": "Auctoritas and potestas are not interchangeable.",
    "analytic_hint": "Classic source for representation, ideology, and the limits of official self-description.",
    "scaffold": [
      "What distinction does Augustus make?",
      "Why is this politically useful?",
      "What sources could test the claim?"
    ],
    "tags": [
      "Augustus",
      "princeps",
      "power",
      "representation",
      "inscription",
      "imperial-image"
    ],
    "recommended_modules": [
      "m05",
      "m09",
      "m10",
      "m11",
      "m17",
      "m18",
      "m22"
    ]
  },
  {
    "id": "dig_1_5_17",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "lat",
    "title": "Legal division of persons",
    "author": "Florentinus / Digest",
    "canonical_ref": "Dig. 1.5.3 / 1.5.5 tradition",
    "period": "6th c. AD compilation of classical juristic material",
    "place": "Roman legal tradition",
    "original_text": "libertas est naturalis facultas eius quod cuique facere libet, nisi si quid vi aut iure prohibetur. servitus est constitutio iuris gentium.",
    "translation_text": "Freedom is the natural capacity to do what each person pleases, unless something is prevented by force or law. Slavery is an institution of the law of nations.",
    "original_source_name": "The Latin Library / Digest excerpt",
    "original_source_url": "https://www.thelatinlibrary.com/justinian/digest1.shtml",
    "translation_source_name": "Adapted standard English legal translation",
    "translation_source_url": "https://droitromain.univ-grenoble-alpes.fr/Corpus/digest.htm",
    "translation_credit": "Scriptorium working translation checked against standard English Digest translations.",
    "context_hint": "Normative juristic definition, not a social survey.",
    "language_hint": "Definitions are precise but highly abstract.",
    "analytic_hint": "Useful for conceptualization and category work; weak as standalone evidence for social practice.",
    "scaffold": [
      "What is being defined?",
      "Is this descriptive or normative?",
      "What social evidence would you need beyond the definition?"
    ],
    "tags": [
      "law",
      "status",
      "slavery",
      "concept",
      "norm-practice"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m09",
      "m11",
      "m20"
    ]
  },
  {
    "id": "claudia_severa_ii_291",
    "primary": true,
    "ready": true,
    "source_type": "writing_tablet",
    "language": "lat",
    "title": "Birthday invitation from Claudia Severa to Lepidina",
    "author": "Claudia Severa",
    "canonical_ref": "Tab. Vindol. 291",
    "period": "c. AD 100",
    "place": "Vindolanda",
    "original_text": "Claudia Severa Lepidinae suae salutem. iii Idus Septembres, soror, ad diem sollemnem natalem meum rogo libenter facias ut venias ad nos.",
    "translation_text": "Claudia Severa to her Lepidina, greetings. On 11 September, sister, for the celebration of my birthday, I ask that you kindly make sure to come to us.",
    "original_source_name": "Vindolanda Tablets Online",
    "original_source_url": "https://vindolanda.csad.ox.ac.uk/TVII-291",
    "translation_source_name": "Vindolanda Tablets Online — English",
    "translation_source_url": "https://vindolanda.csad.ox.ac.uk/TVII-291",
    "translation_credit": "Scriptorium working translation checked against Vindolanda Tablets Online.",
    "context_hint": "Private social correspondence preserved on a wooden writing tablet.",
    "language_hint": "A rare glimpse of informal elite female communication.",
    "analytic_hint": "Excellent as a private-voice control source against official texts.",
    "scaffold": [
      "What makes this source socially valuable?",
      "What remains unrepresentative about it?",
      "How could you pair it with public evidence?"
    ],
    "tags": [
      "letter",
      "women",
      "social-network",
      "private",
      "writing-tablet",
      "Rome"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m14",
      "m21"
    ]
  },
  {
    "id": "p_oxy_3313",
    "primary": true,
    "ready": true,
    "source_type": "papyrus_letter",
    "language": "grc",
    "title": "Tax receipt on papyrus",
    "author": "Local administration",
    "canonical_ref": "P.Oxy. 3313",
    "period": "Roman Egypt",
    "place": "Oxyrhynchus",
    "original_text": "ἀπέσχηκα παρὰ σοῦ τὸ δημόσιον ...",
    "translation_text": "I have received from you the public tax ...",
    "original_source_name": "Papyri.info record",
    "original_source_url": "https://papyri.info/ddbdp/p.oxy;47;3313",
    "translation_source_name": "Papyri.info / record description",
    "translation_source_url": "https://papyri.info/ddbdp/p.oxy;47;3313",
    "translation_credit": "Scriptorium working translation based on the published record description.",
    "context_hint": "Documentary papyrus. Sparse wording, but strong for concrete administrative practice.",
    "language_hint": "Formulaic receipt language often contains little interpretation.",
    "analytic_hint": "Very useful for testing whether broader claims about taxation match documentary practice.",
    "scaffold": [
      "What concrete transaction is documented?",
      "What remains unknown?",
      "Why is documentary brevity also a strength?"
    ],
    "tags": [
      "taxation",
      "economy",
      "documentary",
      "papyrus",
      "procedure",
      "norm-practice"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m08",
      "m10",
      "m11",
      "m21"
    ]
  },
  {
    "id": "ig_ii2_43",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "grc",
    "title": "Decree concerning an alliance",
    "author": "Athenian People",
    "canonical_ref": "IG II² 43",
    "period": "4th c. BC",
    "place": "Athens",
    "original_text": "ἔδοξεν τῷ δήμῳ ... συμμαχίαν εἶναι καὶ φιλίαν ...",
    "translation_text": "It was resolved by the People ... that there shall be alliance and friendship ...",
    "original_source_name": "Attic Inscriptions Online — Greek text",
    "original_source_url": "https://www.atticinscriptions.com/inscription/IGII2/43",
    "translation_source_name": "Attic Inscriptions Online — translation/record",
    "translation_source_url": "https://www.atticinscriptions.com/inscription/IGII2/43",
    "translation_credit": "Scriptorium working translation checked against AIO.",
    "context_hint": "Public decree formula. Be careful not to confuse enacted wording with effective diplomacy.",
    "language_hint": "Formulaic decree language often hides contested politics behind standard phrasing.",
    "analytic_hint": "Strong for institutional wording and public decision, weaker for practical enforcement.",
    "scaffold": [
      "What is formulaic?",
      "What concrete act is performed?",
      "What evidence is missing about implementation?"
    ],
    "tags": [
      "decree",
      "alliance",
      "politics",
      "law",
      "epigraphy",
      "norm-practice"
    ],
    "recommended_modules": [
      "m03",
      "m04",
      "m05",
      "m08",
      "m10",
      "m14"
    ]
  },
  {
    "id": "cil_vi_8797",
    "primary": true,
    "ready": true,
    "source_type": "funerary_inscription",
    "language": "lat",
    "title": "Funerary inscription of a freedwoman",
    "author": "Commemorators",
    "canonical_ref": "CIL VI 8797",
    "period": "Imperial Rome",
    "place": "Rome",
    "original_text": "D(is) M(anibus) ... libertae bene merenti ...",
    "translation_text": "To the spirits of the dead ... for the freedwoman, well deserving ...",
    "original_source_name": "EDCS / CIL record",
    "original_source_url": "https://db.edcs.eu/epigr/epi_url.php?s_sprache=en&p_belegstelle=CIL%2006,%2008797",
    "translation_source_name": "EDCS record / standard expansion",
    "translation_source_url": "https://db.edcs.eu/epigr/epi_url.php?s_sprache=en&p_belegstelle=CIL%2006,%2008797",
    "translation_credit": "Scriptorium working expansion and translation checked against the EDCS record.",
    "context_hint": "Commemorative epigraphy. Public self-representation by family or associates.",
    "language_hint": "Standard formulae matter, but so do the chosen identifiers (status, relation, virtue).",
    "analytic_hint": "Useful for identity and status performance, not a complete biography.",
    "scaffold": [
      "Which identities are foregrounded?",
      "Which are absent?",
      "How far may you infer lived experience?"
    ],
    "tags": [
      "funerary",
      "identity",
      "freedwoman",
      "self-representation",
      "epigraphy"
    ],
    "recommended_modules": [
      "m03",
      "m05",
      "m11",
      "m14",
      "m17",
      "m21"
    ]
  },
  {
    "id": "ocrehadrian_travel",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "lat",
    "title": "Hadrian travel series: Aegyptos",
    "author": "Imperial mint",
    "canonical_ref": "RIC II Hadrian travel series, Aegyptos",
    "period": "AD 134–138",
    "place": "Rome",
    "original_text": "Obv. HADRIANVS AVG COS III P P. Rev. AEGYPTOS; Egypt reclining with ibis / sistrum motif.",
    "translation_text": "Object record: coin of Hadrian presenting the province Egypt as a personified image.",
    "original_source_name": "Online Coins of the Roman Empire — coin record",
    "original_source_url": "https://numismatics.org/ocre/results?q=fulltext%3AAEGYPTOS%20HADRIAN",
    "translation_source_name": "OCRE object data",
    "translation_source_url": "https://numismatics.org/ocre/results?q=fulltext%3AAEGYPTOS%20HADRIAN",
    "translation_credit": "Scriptorium uses OCRE object data.",
    "context_hint": "Imperial provincial personification. Analyze representational politics before historical reality.",
    "language_hint": "Coin legends and images operate together.",
    "analytic_hint": "Excellent for imperial image and representation, weak for provincial reception alone.",
    "scaffold": [
      "What is physically encoded?",
      "What province-image is constructed?",
      "What would reception evidence require?"
    ],
    "tags": [
      "coinage",
      "imperial-image",
      "Hadrian",
      "representation",
      "province",
      "coin"
    ],
    "recommended_modules": [
      "m05",
      "m09",
      "m10",
      "m11",
      "m17"
    ]
  },
  {
    "id": "ocre_nero_temple_janus",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "lat",
    "title": "Nero and the closing of the Temple of Janus",
    "author": "Imperial mint",
    "canonical_ref": "RIC I² Nero 50 (type with PACE P R TERRA MARIQ PARTA IANVM CLVSIT)",
    "period": "AD 65–67",
    "place": "Rome",
    "original_text": "Rev. PACE P R TERRA MARIQ PARTA IANVM CLVSIT. Temple of Janus doors closed.",
    "translation_text": "Object record: “With peace secured for the Roman People on land and sea, he closed Janus.”",
    "original_source_name": "Online Coins of the Roman Empire — coin type",
    "original_source_url": "https://numismatics.org/ocre/id/ric.1(2).ner.50",
    "translation_source_name": "OCRE object data",
    "translation_source_url": "https://numismatics.org/ocre/id/ric.1(2).ner.50",
    "translation_credit": "Scriptorium uses OCRE object data.",
    "context_hint": "Official coin type claiming universal peace.",
    "language_hint": "The legend makes a strong totalizing claim.",
    "analytic_hint": "Perfect for studying political messaging and overclaim.",
    "scaffold": [
      "What is claimed?",
      "What genre conventions amplify the claim?",
      "What independent evidence would test it?"
    ],
    "tags": [
      "coinage",
      "peace",
      "imperial-image",
      "representation",
      "Nero",
      "coin"
    ],
    "recommended_modules": [
      "m01",
      "m05",
      "m09",
      "m10",
      "m17"
    ]
  },
  {
    "id": "ocre_vespasian_judaea",
    "primary": true,
    "ready": true,
    "source_type": "coin",
    "language": "lat",
    "title": "Judaea Capta coin type",
    "author": "Imperial mint",
    "canonical_ref": "RIC II Vespasian Judaea Capta type",
    "period": "AD 71–73",
    "place": "Rome",
    "original_text": "Rev. IVDAEA CAPTA; palm tree with mourning captive figure.",
    "translation_text": "Object record: Vespasianic victory coin proclaiming “Judaea Captured”.",
    "original_source_name": "Online Coins of the Roman Empire — coin search",
    "original_source_url": "https://numismatics.org/ocre/results?q=fulltext%3AIVDAEA%20CAPTA",
    "translation_source_name": "OCRE object data",
    "translation_source_url": "https://numismatics.org/ocre/results?q=fulltext%3AIVDAEA%20CAPTA",
    "translation_credit": "Scriptorium uses OCRE object data.",
    "context_hint": "Victory imagery compresses complex war and provincial experience into a triumphant message.",
    "language_hint": "Caption and iconography work together to frame the conquered province.",
    "analytic_hint": "Use for imperial ideology, not as a full account of the conflict.",
    "scaffold": [
      "What image of victory is presented?",
      "Whose perspective is missing?",
      "What other source types would rebalance the dossier?"
    ],
    "tags": [
      "coinage",
      "imperial-image",
      "war",
      "Judaea",
      "representation",
      "coin"
    ],
    "recommended_modules": [
      "m05",
      "m10",
      "m11",
      "m17",
      "m18"
    ]
  },
  {
    "id": "josephus_bj_6_201",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "grc",
    "title": "Destruction of the Temple in Josephus",
    "author": "Josephus",
    "canonical_ref": "Jos. BJ 6.201",
    "period": "1st c. AD",
    "place": "Judaea / Rome",
    "original_text": "ὁ δὲ ναὸς πᾶς ἐμπίπραται ...",
    "translation_text": "And the whole temple was set on fire ...",
    "original_source_name": "Perseus / Greek text (if unavailable, standard Josephus online edition)",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=J.+BJ+6.201",
    "translation_source_name": "Perseus / English translation (or standard online translation)",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=J.+BJ+6.201&fromdoc=Perseus:text:1999.01.0148",
    "translation_credit": "Scriptorium working translation checked against a standard English Josephus translation.",
    "context_hint": "Narrative historiography by an implicated author with a complex Roman context.",
    "language_hint": "Emotional compression can intensify narrative effect.",
    "analytic_hint": "Useful as a counterweight to triumphal imperial imagery.",
    "scaffold": [
      "What perspective does Josephus bring?",
      "How does narrative differ from coin propaganda?",
      "What can be cross-checked?"
    ],
    "tags": [
      "war",
      "historiography",
      "Judaea",
      "representation",
      "imperialism",
      "literary"
    ],
    "recommended_modules": [
      "m06",
      "m10",
      "m11",
      "m14",
      "m17",
      "m18"
    ]
  },
  {
    "id": "pompeii_cil_iv_5296",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "lat",
    "title": "Pompeian electoral programmata",
    "author": "Unknown wall writers",
    "canonical_ref": "CIL IV 5296",
    "period": "1st c. AD",
    "place": "Pompeii",
    "original_text": "Helvium Sabinum aed(ilem) o(ro) v(os) f(aciatis).",
    "translation_text": "I ask you to make Helvius Sabinus aedile.",
    "original_source_name": "EDR / CIL IV record",
    "original_source_url": "https://db.edcs.eu/epigr/epi_url.php?s_sprache=en&p_belegstelle=CIL%2004,%2005296",
    "translation_source_name": "EDR / standard expansion",
    "translation_source_url": "https://db.edcs.eu/epigr/epi_url.php?s_sprache=en&p_belegstelle=CIL%2004,%2005296",
    "translation_credit": "Scriptorium working expansion and translation checked against epigraphic database conventions.",
    "context_hint": "Street-level electoral inscription; informal yet public.",
    "language_hint": "Programmata are formulaic, but location and brevity matter historically.",
    "analytic_hint": "Excellent for local political communication and the limits of public writing.",
    "scaffold": [
      "Who is speaking?",
      "What action is requested?",
      "What can this not tell you about the election result?"
    ],
    "tags": [
      "politics",
      "Pompeii",
      "inscription",
      "public-writing",
      "election",
      "representation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m21"
    ]
  },
  {
    "id": "tab_hebana_frag",
    "primary": true,
    "ready": true,
    "source_type": "inscription",
    "language": "lat",
    "title": "Tabula Hebana on honours for Germanicus",
    "author": "Roman senate / community copy",
    "canonical_ref": "Tabula Hebana (fragment)",
    "period": "AD 20",
    "place": "Italy",
    "original_text": "... honores Germanico Caesari decernuntur ...",
    "translation_text": "... honours are decreed for Germanicus Caesar ...",
    "original_source_name": "EDCS / inscription record",
    "original_source_url": "https://db.edcs.eu/epigr/epi_url.php?s_sprache=en&p_belegstelle=Tabula%20Hebana",
    "translation_source_name": "Published translation / record description",
    "translation_source_url": "https://db.edcs.eu/epigr/epi_url.php?s_sprache=en&p_belegstelle=Tabula%20Hebana",
    "translation_credit": "Scriptorium working translation based on standard record descriptions.",
    "context_hint": "Inscribed senatorial decree as locally displayed copy.",
    "language_hint": "Public honorific language performs consensus.",
    "analytic_hint": "Good for studying the circulation of central political decisions.",
    "scaffold": [
      "What kind of document is this?",
      "What is being publicly staged?",
      "What is lost in fragmentary preservation?"
    ],
    "tags": [
      "inscription",
      "senate",
      "honours",
      "Germanicus",
      "politics",
      "representation"
    ],
    "recommended_modules": [
      "m04",
      "m05",
      "m10",
      "m11",
      "m17"
    ]
  },
  {
    "id": "theocritus_idyll_15_22",
    "primary": true,
    "ready": true,
    "source_type": "literary",
    "language": "grc",
    "title": "Women moving through the Ptolemaic city",
    "author": "Theocritus",
    "canonical_ref": "Theoc. Id. 15.22–24",
    "period": "3rd c. BC",
    "place": "Alexandria",
    "original_text": "ὦ φίλα, μυρίος ὄχλος· πῶς διεκπεράσομαι;",
    "translation_text": "Dear friend, there is a huge crowd; how shall I get through?",
    "original_source_name": "Perseus Digital Library — Greek text",
    "original_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Theoc.+15.22",
    "translation_source_name": "Perseus Digital Library — English translation",
    "translation_source_url": "https://www.perseus.tufts.edu/hopper/text?doc=Theoc.+15.22&fromdoc=Perseus:text:1999.01.0243",
    "translation_credit": "Scriptorium working translation checked against Perseus.",
    "context_hint": "Literary mimesis with urban observation; neither raw transcript nor pure fiction.",
    "language_hint": "Attend to voice and staging.",
    "analytic_hint": "Useful for questions of urban experience and representation of everyday movement.",
    "scaffold": [
      "What kind of scene is being staged?",
      "What elements may reflect urban reality?",
      "How would you test representativeness?"
    ],
    "tags": [
      "city",
      "women",
      "Alexandria",
      "representation",
      "literary",
      "experience"
    ],
    "recommended_modules": [
      "m05",
      "m09",
      "m11",
      "m14",
      "m17"
    ]
  }
];
