(function(){
'use strict';

const V64_VERSION='6.4';
const V64_PREV_BUILD=window.buildTrainingExercise;
const V64_PREV_RENDER=window.renderExercise;
const V64_PREV_EXERCISE_TEXT=window.exerciseText;
let V64_CORPUS_CACHE=null;

const THEORY64={
 m01:{plain:'Je leert eerst beoordelen of een onderzoek überhaupt kán werken. Niet: “zijn deze bronnen interessant?”, maar: passen onderzoeksvraag, bronnen, methode en conclusie logisch op elkaar?',steps:['Lees eerst de onderzoeksvraag. Markeer welk historisch verschijnsel werkelijk bewezen moet worden.','Vraag per bron: wat kan deze bron rechtstreeks tonen en wat niet?','Controleer of methode en corpus precies dat bewijs kunnen leveren.','Rangschik problemen: eerst wat de conclusie ongeldig maakt, pas daarna kleinere tekortkomingen.','Koppel ieder probleem aan één concrete revisie.'],example:'Een student wil met een keizerlijke munt en een door Tacitus geconstrueerde rede bewijzen “wat de bevolking van het Romeinse rijk dacht over de keizer”. Dat gaat te ver: beide bronnen tonen representaties van macht, geen representatieve opiniepeiling. Een betere vraag kan focussen op hoe macht in verschillende genres wordt voorgesteld en bestreden.',mistakes:['Meteen de broninhoud samenvatten zonder het onderzoeksontwerp te testen.','Een opvallende bron behandelen als representatief voor een hele bevolking.']},
 m02:{plain:'Een goede onderzoeksvraag vraagt precies naar iets dat je bronnen kunnen beantwoorden. De broncapaciteit begrenst dus de ambitie van je vraag.',steps:['Bepaal wat rechtstreeks observeerbaar is.','Kies tijd, ruimte en populatie expliciet.','Definieer het kernbegrip.','Formuleer één hoofdvraag die met dit corpus antwoordbaar is.','Gebruik deelvragen als noodzakelijke stappen naar het hoofdantwoord.'],example:'Als je alleen ere-inscripties hebt, is “hoe populair was de keizer?” te breed. “Hoe construeerden stedelijke elites loyaliteit aan de keizer in ere-inscripties?” sluit veel beter aan op het bewijs.',mistakes:['Een vraag formuleren over intenties of ervaringen waarvoor geen bron bestaat.','Te veel deelvragen die interessant zijn maar niet nodig voor de hoofdvraag.']},
 m03:{plain:'Woorden als democratie, Romanisering, status of sociale mobiliteit zijn geen kant-en-klare meetbare feiten. Je moet eerst beslissen waaraan je ze in bronnen zou herkennen.',steps:['Schrijf een historische werkdefinitie.','Splits het begrip in dimensies.','Maak per dimensie observeerbare indicatoren.','Bedenk false positives: dezelfde indicator kan ook iets anders betekenen.','Bepaal vooraf wanneer je níét van het begrip zult spreken.'],example:'Een Latijnse naam is geen automatische indicator voor “Romanisering”. Die naam kan juridische status, mode, familiepolitiek of epigrafische conventie weerspiegelen. Je hebt dus meerdere onafhankelijke indicatoren nodig.',mistakes:['Een modern begrip ongewijzigd op de oudheid plakken.','Een indicator verwarren met het begrip zelf.']},
 m04:{plain:'Een corpus is een selectie uit wat ooit bestond én uit wat toevallig bewaard is. De samenstelling van je corpus bepaalt dus welke conclusies je mag trekken.',steps:['Definieer de historische populatie waarover je iets wilt zeggen.','Leg inclusie- en exclusiecriteria vast.','Scheid kernbron, controlebron en contextbron.','Onderzoek overleverings- en vindplaatsbias.','Schrijf één expliciete zin over wat je corpus structureel niet kan tonen.'],example:'Als bijna al je inscripties uit rijke stedelijke centra komen, mag je niet zonder meer spreken over “de bevolking van een provincie”. De vindcontext selecteert al vóór jouw analyse.',mistakes:['De best bewaarde casus als normaal behandelen.','Bronnen kiezen omdat ze handig of bekend zijn zonder selectielogica.']},
 m05:{plain:'Bronkritiek betekent niet alleen “de auteur kan biased zijn”. Je moet aantonen hoe productie, doel, publiek, genre en overlevering de maximale bewijskracht van een bron veranderen.',steps:['Noteer wat fysiek/tekstueel rechtstreeks aanwezig is.','Identificeer producent, doel en vermoedelijk publiek.','Bepaal genre en conventies.','Onderzoek selectie en overlevering.','Formuleer de sterkste claim die de bron nog verantwoord kan dragen.'],example:'Een grafinscriptie kan rechtstreeks tonen welke identiteit de nabestaanden wilden tonen. Ze bewijst niet automatisch de volledige sociale identiteit die de overledene in het dagelijks leven had.',mistakes:['“Bias” noemen zonder gevolg voor je conclusie.','Een normatieve tekst behandelen als bewijs dat de norm in praktijk werd gevolgd.']},
 m06:{plain:'Een status quaestionis is een kaart van een debat. Je ordent dus niet per auteur, maar per echt geschilpunt: waar verschillen interpretaties, bronnen of methoden?',steps:['Formuleer het centrale historiografische probleem.','Groepeer onderzoekers per positie of verklaringsmodel.','Benoem waarop ze het wél eens zijn.','Leg uit waarom ze verschillen: ander corpus, andere methode, andere definitie?','Formuleer pas daarna de precieze lacune voor nieuw onderzoek.'],example:'“A zegt X, B zegt Y, C zegt Z” is een literatuurlijst. Sterker is: “Het debat draait om twee verklaringen; positie 1 steunt vooral op literaire bronnen, positie 2 op lokale epigrafie. Daardoor meten zij niet exact hetzelfde verschijnsel.”',mistakes:['Auteur-na-auteur samenvatten.','Een “gap” verzinnen zonder te tonen uit welk debat die voortkomt.']},
 m07:{plain:'Positioneren betekent duidelijk maken welke bestaande interpretatie jouw onderzoek beter kan toetsen, verfijnen of begrenzen. Originaliteit is niet hetzelfde als “niemand deed dit ooit”.',steps:['Benoem de bestaande verklaringen eerlijk.','Selecteer één precieze interventie.','Leg uit welke nieuwe broncombinatie, schaal of methode die interventie mogelijk maakt.','Formuleer wat jouw onderzoek zou kunnen veranderen.','Benoem ook wat mogelijk overeind blijft.'],example:'Een sterke bijdrage kan simpelweg zijn dat je een algemeen model test op lokale variatie. Als het model in drie steden anders werkt, heb je het debat inhoudelijk verfijnd zonder spectaculaire “revolutie”.',mistakes:['Een stroman maken van oudere literatuur.','Originaliteit alleen baseren op een nieuwe casus zonder analytische bijdrage.']},
 m08:{plain:'Een methode is geen decoratief label. Ze moet één concreet inferentieprobleem oplossen: welke stap van bron naar conclusie wordt door deze methode beter controleerbaar?',steps:['Formuleer het inferentieprobleem.','Beschrijf de methode als concrete procedure.','Benoem aannames en benodigde data.','Noteer welke informatie de methode níét kan produceren.','Vergelijk minstens één geloofwaardig alternatief.'],example:'Space syntax kan ruimtelijke toegankelijkheid modelleren, maar niet rechtstreeks intenties of werkelijk voetgangersgedrag bewijzen. De methode is nuttig zolang je die grens bewaakt.',mistakes:['Veel methodetermen stapelen zonder procedure.','Een methode gebruiken omdat die modern of kwantitatief klinkt.']},
 m09:{plain:'Theorie helpt je gericht kijken, maar een model is nooit identiek aan historische werkelijkheid. Je moet theoretische variabelen vertalen naar historische observaties.',steps:['Leg het model in gewone taal uit.','Bepaal welke historische observaties ermee corresponderen.','Maak toetsbare verwachtingen.','Zoek een grensgeval waar het model kan misleiden.','Behandel afwijkingen als informatie, niet als fout in de bron.'],example:'Een principal-agentmodel kan helpen vragen waarom een magistraat afwijkt van verwachtingen, maar “principal” en “agent” zijn jouw analytische categorieën, geen Romeinse zelfbeschrijvingen.',mistakes:['Modeltermen als historische feiten behandelen.','Alle afwijkingen wegverklaren om het model te redden.']},
 m10:{plain:'Triangulatie betekent dat verschillende soorten bewijs elkaar onafhankelijk controleren. Meer bronnen zijn alleen nuttig wanneer hun fouten niet allemaal dezelfde oorsprong hebben.',steps:['Formuleer de claim die je wilt testen.','Noteer per bron welke bias zij heeft.','Zoek een tweede bewijspad met andere productielogica.','Bepaal vooraf wat je doet als bronnen conflicteren.','Maak onderscheid tussen bevestiging en herhaling van hetzelfde perspectief.'],example:'Een keizerlijke munt en een keizerlijke ere-inscriptie kunnen allebei officiële beeldvorming reproduceren. Een particuliere brief of lokale archeologische praktijk kan een onafhankelijker controlepad vormen.',mistakes:['Twee officiële bronnen als volledig onafhankelijke bevestiging tellen.','Tegenstrijdige bronnen gladstrijken in plaats van analyseren.']},
 m11:{plain:'Elke historische conclusie bestaat uit stappen. Je moet kunnen aanwijzen: wat zie ik, wat betekent dat in context, welke inferentie maak ik, en hoe veralgemeen ik?',steps:['Schrijf de observatie zonder interpretatie.','Voeg contextuele betekenis toe.','Formuleer de inferentiestap expliciet.','Bepaal of de stap extra bewijs nodig heeft.','Kalibreer de eindclaim aan de zwakste noodzakelijke stap.'],example:'Observatie: een munt draagt SIGNIS RECEPTIS. Interpretatie: de munt verwijst naar teruggewonnen standaarden. Inferentie: de uitgever presenteert dit als politieke prestatie. Niet automatisch: “alle Romeinen waren hierdoor overtuigd”.',mistakes:['Van brongegeven rechtstreeks naar grote these springen.','Sterke werkwoorden gebruiken waar de inferentie indirect is.']},
 m12:{plain:'Een verklaring is pas sterk wanneer je ook serieuze alternatieven kunt bedenken en bewijs zoekt dat die verklaringen van elkaar onderscheidt.',steps:['Formuleer het waargenomen patroon.','Maak minstens drie verklaringen.','Beschrijf per verklaring het mechanisme.','Voorspel welk bewijs je zou verwachten.','Zoek een observatie waarop de rivalen verschillende voorspellingen doen.'],example:'Meer Latijnse inscripties na een verovering kunnen wijzen op culturele verandering, maar ook op veranderde administratieve epigrafische gewoonten. Alleen chronologie beslist dat niet.',mistakes:['“Na X kwam Y, dus X veroorzaakte Y.”','Alternatieven alleen noemen om ze meteen af te wijzen.']},
 m13:{plain:'Historische datasets zijn vaak onvolledig. Een getal is pas betekenisvol als je begrijpt wat geteld kon worden, wat ontbreekt en welke proxy je werkelijk gebruikt.',steps:['Definieer teller en noemer.','Bepaal wat ontbrekende data veroorzaakt.','Markeer proxies.','Vergelijk alleen periodes/casussen met voldoende vergelijkbare dekking.','Gebruik bandbreedtes of scenario’s wanneer precisie niet verantwoord is.'],example:'Een stijging van het aantal inscripties kan meer activiteit betekenen, maar ook een veranderde “epigraphic habit” of betere conservering. Het ruwe aantal is dus geen directe maat van maatschappelijke intensiteit.',mistakes:['Percentages tonen zonder betrouwbare noemer.','Ontbrekende data behandelen als toevallige leegte.']},
 m14:{plain:'Vergelijken is een onderzoeksontwerp. Je kiest casussen omdat hun overeenkomsten of verschillen een verklaring kunnen testen.',steps:['Formuleer wat precies vergeleken wordt.','Kies most-similar of most-different logica.','Controleer bronvergelijkbaarheid.','Benoem lokale factoren die het patroon kunnen verstoren.','Gebruik afwijkende casussen als stresstest.'],example:'Twee steden met dezelfde juridische status maar sterk verschillende erecultuur kunnen nuttig zijn om lokale elitecompetitie te testen. Twee willekeurige goed bewaarde steden zijn dat niet automatisch.',mistakes:['Casussen kiezen omdat ze bekend zijn.','Lokale variatie als ruis wegzetten.']},
 m15:{plain:'Een hoofdstukstructuur is een argument in grote stappen. Ieder hoofdstuk moet iets bewijzen dat noodzakelijk is voor het antwoord op de hoofdvraag.',steps:['Schrijf de hoofdclaim.','Bepaal welke tussenclaims noodzakelijk zijn.','Koppel elk hoofdstuk aan één tussenclaim.','Voer de schraptest uit.','Zet achtergrond alleen waar ze analytisch nodig is.'],example:'Een hoofdstuk “Historische context” van dertig pagina’s is niet automatisch nuttig. Als geen latere inferentie ervan afhangt, moet het worden ingekort of geïntegreerd.',mistakes:['Hoofdstukken als onderwerpendozen opbouwen.','Achtergrond verwarren met argumentatie.']},
 m16:{plain:'Een goede paragraaf doet één analytische taak. De lezer moet kunnen zien wat de claim is, welk bewijs haar ondersteunt en waarom dat bewijs relevant is.',steps:['Markeer de kernclaim.','Markeer het concrete bewijs.','Schrijf de ontbrekende “dus”-stap uit.','Controleer of alle zinnen dezelfde claim dienen.','Laat de overgang voortkomen uit een nog openstaande vraag.'],example:'“De inscriptie noemt twee Romeinen. Dit bewijst sterke romanisering.” mist de inferentie. Eerst moet je uitleggen waarom naamgeving hier een betrouwbare indicator zou zijn en welke alternatieve verklaringen bestaan.',mistakes:['Bewijs opsommen zonder warrant.','Een nieuwe claim in de laatste zin introduceren.']},
 m17:{plain:'Academische precisie betekent dat je taal exact aangeeft hoe sterk je bewijs is. Voorzichtig schrijven is niet hetzelfde als vaag schrijven.',steps:['Markeer sterke claimwerkwoorden.','Vraag of de bron rechtstreeks of indirect bewijs levert.','Vervang absolute termen door preciezere formuleringen.','Maak tijd, groep en schaal concreet.','Gebruik onzekerheid alleen waar ze inhoudelijk bestaat.'],example:'“Deze bron bewijst dat Britten Rome haatten” is te sterk. “Tacitus construeert in de Calgacus-rede een scherpe literaire kritiek op Romeinse imperiale macht” zegt precies wat de bron wél draagt.',mistakes:['Overal “misschien” schrijven.','Stelligheid gebruiken om onzeker bewijs overtuigender te laten klinken.']},
 m18:{plain:'Een conclusie beantwoordt de oorspronkelijke vraag met dezelfde begrippen en dezelfde bewijsgrenzen. Ze is geen plaats voor een nieuwe these.',steps:['Zet de hoofdvraag letterlijk naast je bevindingen.','Beantwoord iedere deelvraag.','Synthetiseer in plaats van hoofdstukken samen te vatten.','Geef het zekerheidsniveau aan.','Koppel beperkingen aan concrete gevolgen voor de conclusie.'],example:'Een limitation is niet “er waren weinig bronnen”. Sterker: “Omdat private stemmen vrijwel ontbreken, kan deze studie publieke representatie analyseren maar geen representatieve publieke receptie vaststellen.”',mistakes:['Nieuwe verklaringen introduceren in de conclusie.','Limitations als ritueel lijstje zonder gevolg.']},
 m19:{plain:'Peer review is prioriteren. Je zoekt eerst de problemen die geldigheid of bewijslogica bedreigen en pas daarna stijl.',steps:['Vat de bijdrage in één zin samen.','Benoem maximaal drie major issues.','Leg per issue uit welke conclusie daardoor gevaar loopt.','Geef een uitvoerbare revisie.','Bepaal hoe je kunt testen of die revisie geslaagd is.'],example:'Een slecht geformuleerde zin is minor. Een onderzoeksvraag die niet met het gekozen corpus kan worden beantwoord is major en kan het hele cijfer plafonneren.',mistakes:['Twintig kleine opmerkingen geven en het kernprobleem missen.','Kritiek geven zonder revisiestrategie.']},
 m20:{plain:'Hier combineer je alles. Een mini-masterproef is geen lange lijst onderdelen: ieder onderdeel moet de andere begrenzen.',steps:['Begin bij een antwoordbare vraag.','Ontwerp het corpus op die vraag.','Kies methode voor de noodzakelijke inferenties.','Bouw hoofdstukken als bewijsstappen.','Plan rivalen, beperkingen en eindclaim vooraf.'],example:'Als je vraag naar receptie gaat, maar je corpus bestaat alleen uit officiële monumenten, moet je óf de vraag veranderen óf een bronsoort toevoegen die receptie daadwerkelijk kan benaderen.',mistakes:['Eerst een favoriete these kiezen en daarna bewijs zoeken.','Methoden en hoofdstukken toevoegen zonder functie.']},
 m21:{plain:'In het Source Lab leer je eerst traag en precies kijken voordat je een grote historische interpretatie maakt.',steps:['Noteer de bronidentificatie.','Beschrijf alleen wat direct aanwezig is.','Markeer lacunes/restauraties/conventies.','Schrijf mogelijke interpretaties apart.','Bepaal welke vergelijking of controlebron je nodig hebt.'],example:'Bij een beschadigde inscriptie is een editoriale aanvulling tussen vierkante haken geen “gevonden letter”. Noteer dus apart wat steen, editie en interpretatie leveren.',mistakes:['Interpretatie al in de observatie schrijven.','Editoriale reconstructie als fysiek bewijs behandelen.']},
 m22:{plain:'Een mondelinge verdediging test of jij begrijpt waarom je onderzoek zo is ontworpen. Je hoeft niet te doen alsof er geen beperkingen zijn.',steps:['Formuleer je centrale keuze.','Geef het sterkste argument ervoor.','Erken de belangrijkste beperking.','Leg uit hoe je die beperking beheerst.','Beantwoord wat er verandert als een criticus gelijk heeft.'],example:'Sterk antwoord: “Deze inscripties zijn geen representatieve steekproef van alle inwoners; daarom beperk ik mijn claim tot publieke elite-representatie en gebruik ik papyri als controle voor private praktijk.”',mistakes:['Iedere kritiek defensief ontkennen.','Een methodische keuze verdedigen met “zo doet de literatuur het”.']},
 m23:{plain:'Thesis Studio houdt je volledige onderzoek controleerbaar: welke claim wil je bewijzen, welk bewijs draagt haar, welke bezwaren zijn nog open en wat is de volgende onderzoeksactie?',steps:['Maak een claim ledger.','Koppel bronnen aan claims.','Houd tegenargumenten apart bij.','Noteer open onderzoeksrisico’s.','Controleer per hoofdstuk welke claim het moet leveren.'],example:'Als een hoofdstuk veel interessante bronbespreking bevat maar aan geen kernclaim gekoppeld is, zie je dat in de claim ledger meteen als structuurprobleem.',mistakes:['Schrijven gebruiken om nog onopgeloste onderzoekskeuzes te verbergen.','Alle notities als even belangrijk behandelen.']}
};

const PRINCIPLE_MAP64={
 m01:[1,5,9,11,12],m02:[1,7,15],m03:[2,14],m04:[1,5,10],m05:[5,6,9,12],m06:[3,15],m07:[3,15,13],m08:[4,12],m09:[4,14],m10:[5,8,9],m11:[6,9,11],m12:[8,9,13],m13:[9,12,14],m14:[10,13],m15:[7,11],m16:[7,11],m17:[9,11],m18:[11,12],m19:[8,9,11,12],m20:[1,2,4,5,7,8,11,12],m21:[5,6,9],m22:[4,8,9,12],m23:[1,7,11,12]
};

const GENERIC_TAGS64=new Set(['literary','epigraphy','coin','material','documentary','inscription','speech','letter','decree','biography','papyrus','writing-tablet']);
const THEME_GROUPS64={
 'macht & imperium':['empire','imperialism','imperial-image','power','princeps','Augustus','ruler','military'],
 'politiek & instellingen':['democracy','politics','tyranny','Republic','constitution','autonomy','alliance','citizenship','governance'],
 'identiteit & mobiliteit':['identity','migration','Romans','ethnicity','bilingualism','freedwoman','social-network'],
 'religie & ritueel':['religion','ritual','dedication','calendar'],
 'economie & regulering':['economy','coinage','taxation','weights','measures','market','procedure'],
 'representatie & retoriek':['rhetoric','representation','self-representation','historiography','funerary','reception','bias'],
 'norm & praktijk':['law','norm-practice','procedure','decree','governance']
};

function rng64(seed){let h=2166136261>>>0;for(const c of String(seed)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function material64(s){return{authentic:true,synthetic:false,source_id:s.id,label:`${s.canonical_ref} · ${s.title}`,text:s.original_text,translation:s.translation_text,source_type:s.source_type,language:s.language,author:s.author,period:s.period,place:s.place,original_source_name:s.original_source_name,original_source_url:s.original_source_url,translation_source_name:s.translation_source_name,translation_source_url:s.translation_source_url,translation_credit:s.translation_credit,context_hint:s.context_hint,language_hint:s.language_hint,analytic_hint:s.analytic_hint,scaffold:s.scaffold||[],tags:s.tags||[]}}
function themeFor64(srcs){
 const counts=[];
 for(const [name,tags] of Object.entries(THEME_GROUPS64)){let score=0;for(const s of srcs){const st=(s.tags||[]).map(x=>x.toLowerCase());for(const t of tags)if(st.includes(t.toLowerCase()))score++}counts.push([name,score])}
 counts.sort((a,b)=>b[1]-a[1]);return counts[0]?.[1]>0?counts[0][0]:'historische representatie en bewijs';
}
function coherentSources64(moduleId,difficulty,seed){
 const all=(window.V6_AUTHENTIC_SOURCES||[]).filter(s=>s.primary&&s.ready); if(!all.length)return[];
 const r=rng64(seed); const candidates=all.filter(s=>(s.recommended_modules||[]).includes(moduleId)); const anchors=candidates.length?candidates:all; const anchor=anchors[Math.floor(r()*anchors.length)];
 function semantic(s){let score=0;if((s.recommended_modules||[]).includes(moduleId))score+=3; const aTags=(anchor.tags||[]).map(x=>x.toLowerCase()), bTags=(s.tags||[]).map(x=>x.toLowerCase()); for(const [_,group] of Object.entries(THEME_GROUPS64)){const aa=group.some(t=>aTags.includes(t.toLowerCase())),bb=group.some(t=>bTags.includes(t.toLowerCase()));if(aa&&bb)score+=4} for(const t of aTags)if(!GENERIC_TAGS64.has(t)&&bTags.includes(t))score+=2;if(s.source_type!==anchor.source_type)score+=1;return score+r()*0.2}
 const ordered=all.filter(s=>s.id!==anchor.id).map(s=>[s,semantic(s)]).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);
 const n=difficulty>=5?4:difficulty>=3?3:2;return[anchor,...ordered].slice(0,n);
}
function themeQuestion64(theme){
 const m={
  'macht & imperium':'Hoe wordt politieke of imperiale macht in verschillende primaire bronsoorten voorgesteld, gelegitimeerd of bekritiseerd?',
  'politiek & instellingen':'In hoeverre kunnen verschillende bronsoorten institutionele idealen en politieke praktijk van elkaar onderscheiden?',
  'identiteit & mobiliteit':'Hoe worden sociale of collectieve identiteiten in verschillende primaire bronnen geconstrueerd en welke grenzen heeft die representatie?',
  'religie & ritueel':'Wat kunnen normatieve en materiële bronnen samen aantonen over de organisatie en praktijk van cultus?',
  'economie & regulering':'Wat kunnen normatieve, tekstuele en materiële bronnen aantonen over economische regulering en feitelijke praktijk?',
  'representatie & retoriek':'Hoe construeren verschillende genres historische werkelijkheid en welke claims blijven beperkt tot representatie?',
  'norm & praktijk':'In welke mate kunnen voorschriften en andere bronsoorten samen het verschil tussen norm en praktijk benaderen?'
 };return m[theme]||'Welke historische claim kan dit bronnenpakket daadwerkelijk dragen, en waar liggen de inferentiële grenzen?';
}
function researchBrief64(ex,srcs,theme){
 const refs=srcs.map(s=>s.canonical_ref).join('; '), periods=[...new Set(srcs.map(s=>s.period).filter(Boolean))].join(' / '),places=[...new Set(srcs.map(s=>s.place).filter(Boolean))].join(' / ');
 const base={label:'DIDACTISCHE ONDERZOEKSOPZET',title:`Voorstel: ${theme}`,question:themeQuestion64(theme),scope:`Vergelijkende analyse van ${refs}. Datering: ${periods||'zie bronkaarten'}. Plaatsen: ${places||'zie bronkaarten'}.`,corpus:`De onderzoeker kiest deze bronnen omdat zij hetzelfde brede thema vanuit verschillende genres benaderen.`,method:'Vergelijkende close reading + expliciete bronkritiek; observatie, representatie en historische inferentie worden afzonderlijk genoteerd.',claim:`Voorlopige these: de bronnen wijzen gezamenlijk op een herkenbaar patroon binnen ${theme}, dat vervolgens voorzichtig naar een bredere historische interpretatie wordt vertaald.`};
 if(ex.module_id==='m01'){base.question=`In welke mate tonen deze bronnen hoe ${theme} door historische actoren werd ervaren en in praktijk functioneerde?`;base.claim=`Voorlopige these: omdat de bronnen een vergelijkbare spanning tonen, weerspiegelen zij waarschijnlijk een breed gedeelde historische ervaring van ${theme}.`;base.method='De onderzoeker vergelijkt de inhoud van de bronnen en behandelt overeenkomsten als wederzijdse bevestiging.';}
 if(ex.module_id==='m02'){base.label='ONDERZOEKSINTERESSE';base.question='Nog niet geformuleerd — dit is jouw taak.';base.claim='Nog geen these. Formuleer eerst een vraag die het corpus werkelijk kan beantwoorden.';}
 if(ex.module_id==='m03'){base.label='CONCEPTPROBLEEM';base.question=`De onderzoeker wil het begrip “${theme}” als centrale analytische categorie gebruiken.`;base.claim='Nog vóór de analyse moet duidelijk worden welke indicatoren wel en niet onder het begrip vallen.';}
 if(ex.module_id==='m04'){base.label='CORPUSPROBLEEM';base.question=`Doelpopulatie: alle relevante historische actoren binnen het thema ${theme}.`;base.claim=`De huidige bronnen zijn kandidaat-kerncorpus; jij moet bepalen welke rol elke bron mag krijgen en welke populatie daarmee werkelijk bereikbaar is.`;}
 if(ex.module_id==='m05'){base.label='HISTORISCHE VRAAG';base.question=themeQuestion64(theme);base.claim='Bepaal eerst per bron de maximale inferentie vóór je de bronnen combineert.';}
 if(['m08','m09','m10','m11','m12','m14'].includes(ex.module_id)){base.label='ANALYTISCH ONDERZOEKSPROBLEEM';}
 if(ex.module_id==='m15'){base.label='VOORGESTELDE THESISSTRUCTUUR';base.method='Voorlopige hoofdstukken: 1) context en begrippen; 2) eerste broncluster; 3) tweede broncluster; 4) vergelijking; 5) conclusie. Jij moet beoordelen welke hoofdstukken echte bewijsstappen zijn.';}
 if(['m16','m17'].includes(ex.module_id)){base.label='DIDACTISCH STUDENTFRAGMENT';base.method='Studentclaim: “Omdat meerdere bronnen vergelijkbare elementen tonen, bewijst dit dat het beschreven verschijnsel breed in de samenleving aanwezig was.” Gebruik dit als te analyseren formulering; het is géén primaire bron.';}
 if(ex.module_id==='m18'){base.label='VOORLOPIGE BEVINDINGEN';base.claim=`Voorlopig resultaat: de bronnen tonen een herhaald patroon rond ${theme}, maar representativiteit en bronfunctie verschillen sterk. Ontwerp een conclusie die dat verschil bewaart.`;}
 if(ex.module_id==='m19'){base.label='TE REVIEWEN ONDERZOEKSONTWERP';}
 if(ex.module_id==='m20'){base.label='STARTDOSSIER MINI-MASTERPROEF';base.question='Nog open: ontwerp zelf een antwoordbare hoofdvraag op basis van dit dossier.';base.claim='Nog geen vooraf gekozen these.';}
 if(ex.module_id==='m22'){base.label='TE VERDEDIGEN ONDERZOEKSONTWERP';}
 if(ex.module_id==='m23'){base.label='THESIS-STUDIO STARTKAART';base.claim='Bouw zelf een claim ledger; voorkom dat een voorlopige interpretatie ongemerkt als bewezen these wordt behandeld.';}
 return base;
}
function supportText64(b){return`ONDERZOEKSKADER\nType: ${b.label}\nTitel: ${b.title}\nOnderzoeksvraag/doel: ${b.question}\nVoorlopige claim: ${b.claim}\nAfbakening: ${b.scope}\nCorpuslogica: ${b.corpus}\nMethode/werkwijze: ${b.method}`}

window.buildTrainingExercise=function(moduleId,difficulty,mode,requestedMaterial,seed){
 const ex=V64_PREV_BUILD(moduleId,difficulty,mode,requestedMaterial,seed); const srcs=coherentSources64(moduleId,difficulty,seed); if(srcs.length)ex.materials=srcs.map(material64); const theme=themeFor64(srcs); ex.research_brief=researchBrief64(ex,srcs,theme); ex.intro=`Je krijgt hieronder eerst het onderzoeks- of analyseprobleem en daarna ${srcs.length} authentieke primaire bron${srcs.length===1?'':'nen'}. Alle noodzakelijke basiscontext staat zichtbaar; extra hulp blijft optioneel.`;
 if(moduleId==='m06'||moduleId==='m07'){const b=trainingBenchmarks(TRAINING_MODULES.find(m=>m.id===moduleId)).slice(0,4);ex.scholar_positions=b.map((x,i)=>({label:`Onderzoekspositie ${i+1}`,author:x.source,work:x.work,principle:x.principle,why:x.why,limit:x.limit,evidence:x.evidence||[]}));}
 ex.expected={...(ex.expected||{}),research_brief:ex.research_brief,theme,authentic_sources:srcs.map(s=>({id:s.id,ref:s.canonical_ref,type:s.source_type}))}; ex.signature=`${moduleId}|${ex.family}|V64|${theme}|${srcs.map(s=>s.id).join('+')}|${difficulty}`;
 return ex;
};

function briefHTML64(b){if(!b)return'';return`<section class="v64-brief"><div class="v64-eyebrow">${esc(b.label)}</div><h3>${esc(b.title)}</h3><div class="v64-brief-grid"><div><span>Onderzoeksvraag / doel</span><p>${esc(b.question)}</p></div><div><span>Voorlopige claim</span><p>${esc(b.claim)}</p></div><div><span>Afbakening</span><p>${esc(b.scope)}</p></div><div><span>Corpuslogica</span><p>${esc(b.corpus)}</p></div><div class="wide"><span>Methode / werkwijze</span><p>${esc(b.method)}</p></div></div><div class="v64-note"><strong>Wat moet jij doen?</strong> Beoordeel of deze opzet en de onderstaande bronnen elkaar werkelijk dragen. Je hoeft geen historische feiten te kennen die niet in het dossier staan.</div></section>`}
function scholarHTML64(arr){if(!arr?.length)return'';return`<section class="v64-scholars"><div class="v64-eyebrow">ECHTE ONDERZOEKSPOSITIES UIT HET CORPUS</div><h3>Materiaal voor historiografische analyse</h3>${arr.map(x=>`<article><strong>${esc(x.author||'Auteur')} — ${esc(x.work||'werk')}</strong><p>${esc(x.principle||'')}</p>${x.why?`<p class="tiny"><b>Waarom relevant:</b> ${esc(x.why)}</p>`:''}<div class="tiny">${(x.evidence||[]).map(e=>`${esc(e.author||x.author||'')} · fysieke PDF-p. ${esc(e.physical_page||'?')}`).join(' · ')}</div></article>`).join('')}</section>`}

window.renderExercise=function(){
 V64_PREV_RENDER(); const ex=state.currentExercise,body=document.querySelector('#exerciseBody');if(!ex||!body)return; const grid=body.querySelector('.material-grid');if(grid&&!body.querySelector('.v64-brief'))grid.insertAdjacentHTML('beforebegin',briefHTML64(ex.research_brief)+scholarHTML64(ex.scholar_positions));
 body.querySelectorAll('.material.authentic').forEach((card,i)=>{const m=ex.materials?.[i];if(!m||card.querySelector('.v64-context'))return;const head=card.querySelector('.auth-source-meta')||card.querySelector('.primary-source-head');if(head)head.insertAdjacentHTML('afterend',`<div class="v64-context"><strong>Basiscontext</strong><span>${esc(m.context_hint||'Gebruik auteur, datering, plaats, genre en provenance uit de bronkaart als uitgangspunt.')}</span></div>`)});
};

window.exerciseText=function(ex){
 const brief=ex.research_brief?`\n${supportText64(ex.research_brief)}\n`:''; const scholars=(ex.scholar_positions||[]).map(x=>`\n--- ${x.label}: ${x.author}, ${x.work} ---\n${x.principle}\n${x.why||''}`).join(''); const mats=(ex.materials||[]).map((m,i)=>`\n--- PRIMAIRE BRON ${i+1}: ${m.label} ---\nBASISCONTEXT: ${m.context_hint||''}\nORIGINEEL/OBJECTDATA:\n${m.text}\nENGLISH:\n${m.translation||''}\nHERKOMST: ${m.original_source_url||''}\nTRANSLATION/CHECK: ${m.translation_source_url||''}`).join('\n'); return `${ex.title}\nVariatie-ID: ${ex.signature}\nMoeilijkheid: ${ex.difficulty}/5 · modus: ${ex.mode}\n${ex.intro}${brief}${scholars}${mats}\n\nOPDRACHT\n${ex.prompt}`;
};

async function corpus64(){if(V64_CORPUS_CACHE)return V64_CORPUS_CACHE;try{const r=await fetch('./corpus_seed.json',{cache:'no-store'});V64_CORPUS_CACHE=await r.json();return V64_CORPUS_CACHE}catch(e){return null}}
function evidenceHTML64(e){return`<div class="v64-evidence"><b>${esc(e.author||'Auteur')}</b> · fysieke PDF-p. ${esc(e.physical_page||'?')}<br><span>${esc(e.description||'')}</span></div>`}
function sourceWorked64(m){const all=(window.V6_AUTHENTIC_SOURCES||[]).filter(s=>s.primary&&s.ready&&(s.recommended_modules||[]).includes(m.id));const s=all[0]||(window.V6_AUTHENTIC_SOURCES||[])[0];if(!s)return'';return`<div class="v64-worked"><div class="v64-eyebrow">CONCREET VOORBEELD MET EEN ECHTE BRON</div><h3>${esc(s.canonical_ref)} · ${esc(s.title)}</h3><p><b>Wat zie je rechtstreeks?</b> ${esc((s.original_text||'').slice(0,260))}${(s.original_text||'').length>260?'…':''}</p><p><b>Waarom is dat nog geen eindconclusie?</b> ${esc(s.analytic_hint||s.context_hint||'De bron heeft een specifieke productiecontext en maximale inferentie.')}</p><p><b>Denkstap:</b> noteer eerst observatie → bronfunctie → mogelijke inferentie → welke extra bron je nodig hebt om verder te gaan.</p><div class="source-links"><a target="_blank" rel="noopener" href="${esc(s.original_source_url||'#')}">Open originele editie/record ↗</a><a target="_blank" rel="noopener" href="${esc(s.translation_source_url||'#')}">Open Engelse vertaling/check ↗</a></div></div>`}

window.openModuleTheory=async function(moduleId){
 const m=TRAINING_MODULES.find(x=>x.id===moduleId)||TRAINING_MODULES[0],t=THEORY64[m.id]||{plain:m.desc,steps:[m.desc],example:'Pas het principe toe op één concrete bron voordat je veralgemeent.',mistakes:['Te snel abstraheren.']}; const seed=await corpus64(); const ranks=PRINCIPLE_MAP64[m.id]||[]; const principles=(seed?.cross_corpus_principles||[]).filter(p=>ranks.includes(p.rank)).slice(0,4); const seen=await v6SettingsGet('v6_theory_seen',{});seen[m.id]=Date.now();await v6SettingsPut('v6_theory_seen',seen);window.V6_THEORY_MODULE=m.id;
 document.querySelector('#theoryTitle').textContent=`Module ${m.n} · ${m.title}`;
 document.querySelector('#theoryMain').innerHTML=`
  <section class="theory-block v64-intro"><div class="v64-eyebrow">EERST IN GEWONE TAAL</div><h3>Wat leer je hier eigenlijk?</h3><p class="v64-lead">${esc(t.plain)}</p></section>
  <section class="theory-block"><div class="v64-eyebrow">STAPPENPLAN</div><h3>Zo pak je het aan</h3><ol class="v64-steps">${t.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section>
  <section class="theory-block v64-example"><div class="v64-eyebrow">EERST EEN EENVOUDIG VOORBEELD</div><h3>Hoe ziet dat concreet eruit?</h3><p>${esc(t.example)}</p></section>
  ${sourceWorked64(m)}
  <section class="theory-block"><div class="v64-eyebrow">WAAROM DIT GEEN LOSSE AI-REGEL IS</div><h3>Voorbeelden uit de 56 echte papers</h3>${principles.length?principles.map(p=>`<article class="v64-principle"><h4>${esc(p.principle)}</h4><p>${esc(p.why||'')}</p>${(p.evidence||[]).slice(0,3).map(evidenceHTML64).join('')}<p class="v64-practice"><b>Zelf oefenen:</b> ${esc(p.practice||'Pas dit principe op je eigen ontwerp toe.')}</p></article>`).join(''):'<p>De gekoppelde corpusprincipes konden niet geladen worden. De oefening blijft beschikbaar.</p>'}</section>
  <section class="theory-block v64-mistakes"><div class="v64-eyebrow">VEELGEMAAKTE FOUTEN</div><h3>Hier moet je voor oppassen</h3><ul>${t.mistakes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>
  <section class="theory-block v64-ready"><div class="v64-eyebrow">KORTE ZELFTEST</div><h3>Je bent klaar voor de oefening als…</h3><p>…je in je eigen woorden kunt uitleggen <b>welke stap van bron naar conclusie</b> deze module controleert en <b>waarom een aantrekkelijke conclusie soms toch te sterk is</b>.</p></section>`;
 showPage('training-theory');
};

const oldInit64=window.init;
window.init=async function(){if(oldInit64)await oldInit64();document.title='Scriptorium V6.5 - Academische Onderzoekscoach';document.querySelectorAll('.version-pill').forEach(x=>x.textContent='V6.5');const s=document.querySelector('.brand small');if(s)s.textContent='Onderzoekscoach V6.5 · duidelijke theorie · complete oefendossiers · uitgebreide authentieke bronnen';const sub=document.querySelector('.topbar-sub');if(sub)sub.textContent='Scriptorium V6.5 · theorie → voorbeeld → authentieke oefening';const btn=document.querySelector('#openSelectedTheory');if(btn)btn.onclick=()=>window.openModuleTheory(document.querySelector('#trainingModule').value);};
})();
